// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Bandwidth.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Bandwidth.OpenApiClient.MyNumbers.Tns.Item.Tndetails
{
    /// <summary>
    /// Builds and executes requests for operations under \my-numbers\tns\{tn}\tndetails
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TndetailsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bandwidth.OpenApiClient.MyNumbers.Tns.Item.Tndetails.TndetailsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TndetailsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/my-numbers/tns/{tn}/tndetails", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bandwidth.OpenApiClient.MyNumbers.Tns.Item.Tndetails.TndetailsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TndetailsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/my-numbers/tns/{tn}/tndetails", rawUrl)
        {
        }
        /// <summary>
        /// Retrieves detailed information about the phone number.In this table are presented capabilities that are not universally available. The following response body attributes are only returned for numbers from specific region/country:| Number Region | Response Body Attributes ||:--------------|:------------------------||NANP|LATA||NANP|State||NANP|RateCenter||NANP|E911|These parameters are only applicable and hence returned in response body for North American Numbering Plan phone numbers.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bandwidth.OpenApiClient.Models.TelephoneNumberDetailHistoryResponseJson"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Bandwidth.OpenApiClient.Models.TelephoneNumbersErrorResponseJson">When receiving a 400 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Bandwidth.OpenApiClient.Models.TelephoneNumberDetailHistoryResponseJson?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Bandwidth.OpenApiClient.Models.TelephoneNumberDetailHistoryResponseJson> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Bandwidth.OpenApiClient.Models.TelephoneNumbersErrorResponseJson.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Bandwidth.OpenApiClient.Models.TelephoneNumberDetailHistoryResponseJson>(requestInfo, global::Soenneker.Bandwidth.OpenApiClient.Models.TelephoneNumberDetailHistoryResponseJson.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieves detailed information about the phone number.In this table are presented capabilities that are not universally available. The following response body attributes are only returned for numbers from specific region/country:| Number Region | Response Body Attributes ||:--------------|:------------------------||NANP|LATA||NANP|State||NANP|RateCenter||NANP|E911|These parameters are only applicable and hence returned in response body for North American Numbering Plan phone numbers.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bandwidth.OpenApiClient.MyNumbers.Tns.Item.Tndetails.TndetailsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Bandwidth.OpenApiClient.MyNumbers.Tns.Item.Tndetails.TndetailsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Bandwidth.OpenApiClient.MyNumbers.Tns.Item.Tndetails.TndetailsRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
