// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Bandwidth.OpenApiClient.Accounts.Item.Sites;
using Soenneker.Bandwidth.OpenApiClient.Accounts.Item.TotalSeats;
using Soenneker.Bandwidth.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Bandwidth.OpenApiClient.Accounts.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \accounts\{accountId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithAccountItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The sites property</summary>
        public global::Soenneker.Bandwidth.OpenApiClient.Accounts.Item.Sites.SitesRequestBuilder Sites
        {
            get => new global::Soenneker.Bandwidth.OpenApiClient.Accounts.Item.Sites.SitesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The totalSeats property</summary>
        public global::Soenneker.Bandwidth.OpenApiClient.Accounts.Item.TotalSeats.TotalSeatsRequestBuilder TotalSeats
        {
            get => new global::Soenneker.Bandwidth.OpenApiClient.Accounts.Item.TotalSeats.TotalSeatsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bandwidth.OpenApiClient.Accounts.Item.WithAccountItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithAccountItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/accounts/{accountId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bandwidth.OpenApiClient.Accounts.Item.WithAccountItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithAccountItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/accounts/{accountId}", rawUrl)
        {
        }
        /// <summary>
        /// &quot;The account is the root resource for many of the operations in the Bandwidth App.The account is represented by an account ID, which is the resource that represents a Bandwidth customer, providing a root resource for all of the customer&apos;s attributes and services.The API calls that are used to manage the details of a customer account, and to manage the resources that a Bandwidth customer has access to or control over, are accessed through the /accounts resource.This API call retrieves information about the account indicated by the Account ID.**Addresses**: `Address` and `LinkedAddresses`- Address   - The service address of the account. Historically only US and Canadian addresses supported.  - `Address` will continue to be populated as long as the address is US/ Canada based and only one linked address exists.- LinkedAddresses   - A list of address reference IDs that are linked at the account.   - These addresses can be fully international.  - `LinkedAddresses` will replace `Address`, however will continue to be supported for US/ Canada addresses.    - A list of **one** address will be supported initially, however this will extend as more address usages are introduced.  - `LinkedAddresses` can be created and managed through the /addresses resource. See: [Addresses](https://dev.bandwidth.com/apis/numbers-apis/end-user-management/#tag/Addresses/operation/createAddress) for more information.  - A link to the individual Address API is returned within this object, see `Link`.&quot;
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bandwidth.OpenApiClient.Models.AccountJson_1"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Bandwidth.OpenApiClient.Models.ErrorResponseJson_1">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Bandwidth.OpenApiClient.Models.ErrorResponseJson_1">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Bandwidth.OpenApiClient.Models.AccountJson_1?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Bandwidth.OpenApiClient.Models.AccountJson_1> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "404", global::Soenneker.Bandwidth.OpenApiClient.Models.ErrorResponseJson_1.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Bandwidth.OpenApiClient.Models.ErrorResponseJson_1.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Bandwidth.OpenApiClient.Models.AccountJson_1>(requestInfo, global::Soenneker.Bandwidth.OpenApiClient.Models.AccountJson_1.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &quot;The account is the root resource for many of the operations in the Bandwidth App.The account is represented by an account ID, which is the resource that represents a Bandwidth customer, providing a root resource for all of the customer&apos;s attributes and services.The API calls that are used to manage the details of a customer account, and to manage the resources that a Bandwidth customer has access to or control over, are accessed through the /accounts resource.This API call retrieves information about the account indicated by the Account ID.**Addresses**: `Address` and `LinkedAddresses`- Address   - The service address of the account. Historically only US and Canadian addresses supported.  - `Address` will continue to be populated as long as the address is US/ Canada based and only one linked address exists.- LinkedAddresses   - A list of address reference IDs that are linked at the account.   - These addresses can be fully international.  - `LinkedAddresses` will replace `Address`, however will continue to be supported for US/ Canada addresses.    - A list of **one** address will be supported initially, however this will extend as more address usages are introduced.  - `LinkedAddresses` can be created and managed through the /addresses resource. See: [Addresses](https://dev.bandwidth.com/apis/numbers-apis/end-user-management/#tag/Addresses/operation/createAddress) for more information.  - A link to the individual Address API is returned within this object, see `Link`.&quot;
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bandwidth.OpenApiClient.Accounts.Item.WithAccountItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Bandwidth.OpenApiClient.Accounts.Item.WithAccountItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Bandwidth.OpenApiClient.Accounts.Item.WithAccountItemRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
