// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Bandwidth.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Bandwidth.OpenApiClient.Tendlc.Accounts.Item.Tendlc.Campaigns.Item.PhoneNumbers
{
    /// <summary>
    /// Builds and executes requests for operations under \tendlc\accounts\{accountId}\tendlc\campaigns\{campaignId}\phoneNumbers
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PhoneNumbersRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bandwidth.OpenApiClient.Tendlc.Accounts.Item.Tendlc.Campaigns.Item.PhoneNumbers.PhoneNumbersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PhoneNumbersRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/tendlc/accounts/{accountId}/tendlc/campaigns/{campaignId}/phoneNumbers{?createdDate*,customerProfileId*,limit*,modifiedDate*,offset*,phoneNumber*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bandwidth.OpenApiClient.Tendlc.Accounts.Item.Tendlc.Campaigns.Item.PhoneNumbers.PhoneNumbersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PhoneNumbersRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/tendlc/accounts/{accountId}/tendlc/campaigns/{campaignId}/phoneNumbers{?createdDate*,customerProfileId*,limit*,modifiedDate*,offset*,phoneNumber*}", rawUrl)
        {
        }
        /// <summary>
        /// **All customers.** Get all phone numbers associated with a campaign. This includes numbers that are correctly assigned and numbers that Bandwidth believes to be currently registered to the campaign in external systems due to provisioning errors.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bandwidth.OpenApiClient.Models.GetCampaignPhoneNumbersResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Bandwidth.OpenApiClient.Models.Tendlc_errorResponse400">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Bandwidth.OpenApiClient.Models.Tendlc_errorResponse401">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Bandwidth.OpenApiClient.Models.Tendlc_errorResponse403">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Bandwidth.OpenApiClient.Models.Tendlc_errorResponse404">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Bandwidth.OpenApiClient.Models.Tendlc_errorResponse405">When receiving a 405 status code</exception>
        /// <exception cref="global::Soenneker.Bandwidth.OpenApiClient.Models.Tendlc_errorResponse500">When receiving a 500 status code</exception>
        /// <exception cref="global::Soenneker.Bandwidth.OpenApiClient.Models.Tendlc_errorResponse503">When receiving a 503 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Bandwidth.OpenApiClient.Models.GetCampaignPhoneNumbersResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.Bandwidth.OpenApiClient.Tendlc.Accounts.Item.Tendlc.Campaigns.Item.PhoneNumbers.PhoneNumbersRequestBuilder.PhoneNumbersRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Bandwidth.OpenApiClient.Models.GetCampaignPhoneNumbersResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.Bandwidth.OpenApiClient.Tendlc.Accounts.Item.Tendlc.Campaigns.Item.PhoneNumbers.PhoneNumbersRequestBuilder.PhoneNumbersRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Bandwidth.OpenApiClient.Models.Tendlc_errorResponse400.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Bandwidth.OpenApiClient.Models.Tendlc_errorResponse401.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Bandwidth.OpenApiClient.Models.Tendlc_errorResponse403.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Bandwidth.OpenApiClient.Models.Tendlc_errorResponse404.CreateFromDiscriminatorValue },
                { "405", global::Soenneker.Bandwidth.OpenApiClient.Models.Tendlc_errorResponse405.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Bandwidth.OpenApiClient.Models.Tendlc_errorResponse500.CreateFromDiscriminatorValue },
                { "503", global::Soenneker.Bandwidth.OpenApiClient.Models.Tendlc_errorResponse503.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Bandwidth.OpenApiClient.Models.GetCampaignPhoneNumbersResponse>(requestInfo, global::Soenneker.Bandwidth.OpenApiClient.Models.GetCampaignPhoneNumbersResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// **All customers.** Get all phone numbers associated with a campaign. This includes numbers that are correctly assigned and numbers that Bandwidth believes to be currently registered to the campaign in external systems due to provisioning errors.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Bandwidth.OpenApiClient.Tendlc.Accounts.Item.Tendlc.Campaigns.Item.PhoneNumbers.PhoneNumbersRequestBuilder.PhoneNumbersRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Bandwidth.OpenApiClient.Tendlc.Accounts.Item.Tendlc.Campaigns.Item.PhoneNumbers.PhoneNumbersRequestBuilder.PhoneNumbersRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bandwidth.OpenApiClient.Tendlc.Accounts.Item.Tendlc.Campaigns.Item.PhoneNumbers.PhoneNumbersRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Bandwidth.OpenApiClient.Tendlc.Accounts.Item.Tendlc.Campaigns.Item.PhoneNumbers.PhoneNumbersRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Bandwidth.OpenApiClient.Tendlc.Accounts.Item.Tendlc.Campaigns.Item.PhoneNumbers.PhoneNumbersRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// **All customers.** Get all phone numbers associated with a campaign. This includes numbers that are correctly assigned and numbers that Bandwidth believes to be currently registered to the campaign in external systems due to provisioning errors.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class PhoneNumbersRequestBuilderGetQueryParameters 
        {
            /// <summary>Sorting and filtering parameter for `createdDate`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("createdDate")]
            public string? CreatedDate { get; set; }
#nullable restore
#else
            [QueryParameter("createdDate")]
            public string CreatedDate { get; set; }
#endif
            /// <summary>Filtering parameter for `customerProfileId`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("customerProfileId")]
            public string? CustomerProfileId { get; set; }
#nullable restore
#else
            [QueryParameter("customerProfileId")]
            public string CustomerProfileId { get; set; }
#endif
            /// <summary>Limit (page size) for pagination</summary>
            [QueryParameter("limit")]
            public double? Limit { get; set; }
            /// <summary>Sorting parameter for `modifiedDate`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("modifiedDate")]
            public string? ModifiedDate { get; set; }
#nullable restore
#else
            [QueryParameter("modifiedDate")]
            public string ModifiedDate { get; set; }
#endif
            /// <summary>Offset for pagination (from zero, the first returned record)</summary>
            [QueryParameter("offset")]
            public double? Offset { get; set; }
            /// <summary>Filtering and sorting parameter for `phoneNumber`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("phoneNumber")]
            public string? PhoneNumber { get; set; }
#nullable restore
#else
            [QueryParameter("phoneNumber")]
            public string PhoneNumber { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
