// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Bandwidth.OpenApiClient.DashNotifications.Notifications.Endpoints.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Bandwidth.OpenApiClient.DashNotifications.Notifications.Endpoints
{
    /// <summary>
    /// Builds and executes requests for operations under \dash-notifications\notifications\endpoints
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EndpointsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Bandwidth.OpenApiClient.dashNotifications.notifications.endpoints.item collection</summary>
        /// <param name="position">endpointId</param>
        /// <returns>A <see cref="global::Soenneker.Bandwidth.OpenApiClient.DashNotifications.Notifications.Endpoints.Item.WithEndpointItemRequestBuilder"/></returns>
        public global::Soenneker.Bandwidth.OpenApiClient.DashNotifications.Notifications.Endpoints.Item.WithEndpointItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("endpointId", position);
                return new global::Soenneker.Bandwidth.OpenApiClient.DashNotifications.Notifications.Endpoints.Item.WithEndpointItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bandwidth.OpenApiClient.DashNotifications.Notifications.Endpoints.EndpointsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EndpointsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/dash-notifications/notifications/endpoints", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bandwidth.OpenApiClient.DashNotifications.Notifications.Endpoints.EndpointsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EndpointsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/dash-notifications/notifications/endpoints", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
