// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Bandwidth.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Bandwidth.OpenApiClient.Global.Subscriptions.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \global\subscriptions\{subscriptionId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithSubscriptionItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bandwidth.OpenApiClient.Global.Subscriptions.Item.WithSubscriptionItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithSubscriptionItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/global/subscriptions/{subscriptionId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bandwidth.OpenApiClient.Global.Subscriptions.Item.WithSubscriptionItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithSubscriptionItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/global/subscriptions/{subscriptionId}", rawUrl)
        {
        }
        /// <summary>
        /// Delete Subscription
        /// </summary>
        /// <returns>A <see cref="Stream"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Bandwidth.OpenApiClient.Models.ResponseProperties_1">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Bandwidth.OpenApiClient.Models.ResponseProperties_1">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Bandwidth.OpenApiClient.Models.ResponseProperties_1">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Bandwidth.OpenApiClient.Models.ResponseProperties_1">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Bandwidth.OpenApiClient.Models.ResponseProperties_1">When receiving a 405 status code</exception>
        /// <exception cref="global::Soenneker.Bandwidth.OpenApiClient.Models.ResponseProperties_1">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<Stream?> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<Stream> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Bandwidth.OpenApiClient.Models.ResponseProperties_1.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Bandwidth.OpenApiClient.Models.ResponseProperties_1.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Bandwidth.OpenApiClient.Models.ResponseProperties_1.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Bandwidth.OpenApiClient.Models.ResponseProperties_1.CreateFromDiscriminatorValue },
                { "405", global::Soenneker.Bandwidth.OpenApiClient.Models.ResponseProperties_1.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Bandwidth.OpenApiClient.Models.ResponseProperties_1.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendPrimitiveAsync<Stream>(requestInfo, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// GET Subscription by ID
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bandwidth.OpenApiClient.Global.Subscriptions.Item.WithSubscriptionGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Bandwidth.OpenApiClient.Models.ResponseProperties_1">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Bandwidth.OpenApiClient.Models.ResponseProperties_1">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Bandwidth.OpenApiClient.Models.ResponseProperties_1">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Bandwidth.OpenApiClient.Models.ResponseProperties_1">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Bandwidth.OpenApiClient.Models.ResponseProperties_1">When receiving a 405 status code</exception>
        /// <exception cref="global::Soenneker.Bandwidth.OpenApiClient.Models.ResponseProperties_1">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Bandwidth.OpenApiClient.Global.Subscriptions.Item.WithSubscriptionGetResponse?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Bandwidth.OpenApiClient.Global.Subscriptions.Item.WithSubscriptionGetResponse> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Bandwidth.OpenApiClient.Models.ResponseProperties_1.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Bandwidth.OpenApiClient.Models.ResponseProperties_1.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Bandwidth.OpenApiClient.Models.ResponseProperties_1.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Bandwidth.OpenApiClient.Models.ResponseProperties_1.CreateFromDiscriminatorValue },
                { "405", global::Soenneker.Bandwidth.OpenApiClient.Models.ResponseProperties_1.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Bandwidth.OpenApiClient.Models.ResponseProperties_1.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Bandwidth.OpenApiClient.Global.Subscriptions.Item.WithSubscriptionGetResponse>(requestInfo, global::Soenneker.Bandwidth.OpenApiClient.Global.Subscriptions.Item.WithSubscriptionGetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Modify Subscription
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bandwidth.OpenApiClient.Global.Subscriptions.Item.WithSubscriptionPatchResponse"/></returns>
        /// <param name="body">Modify Subscription Model</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Bandwidth.OpenApiClient.Models.ResponseProperties_1">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Bandwidth.OpenApiClient.Models.ResponseProperties_1">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Bandwidth.OpenApiClient.Models.ResponseProperties_1">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Bandwidth.OpenApiClient.Models.ResponseProperties_1">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Bandwidth.OpenApiClient.Models.ResponseProperties_1">When receiving a 405 status code</exception>
        /// <exception cref="global::Soenneker.Bandwidth.OpenApiClient.Models.ResponseProperties_1">When receiving a 409 status code</exception>
        /// <exception cref="global::Soenneker.Bandwidth.OpenApiClient.Models.ResponseProperties_1">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Bandwidth.OpenApiClient.Global.Subscriptions.Item.WithSubscriptionPatchResponse?> PatchAsync(global::Soenneker.Bandwidth.OpenApiClient.Models.ModifySubscription_1 body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Bandwidth.OpenApiClient.Global.Subscriptions.Item.WithSubscriptionPatchResponse> PatchAsync(global::Soenneker.Bandwidth.OpenApiClient.Models.ModifySubscription_1 body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPatchRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Bandwidth.OpenApiClient.Models.ResponseProperties_1.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Bandwidth.OpenApiClient.Models.ResponseProperties_1.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Bandwidth.OpenApiClient.Models.ResponseProperties_1.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Bandwidth.OpenApiClient.Models.ResponseProperties_1.CreateFromDiscriminatorValue },
                { "405", global::Soenneker.Bandwidth.OpenApiClient.Models.ResponseProperties_1.CreateFromDiscriminatorValue },
                { "409", global::Soenneker.Bandwidth.OpenApiClient.Models.ResponseProperties_1.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Bandwidth.OpenApiClient.Models.ResponseProperties_1.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Bandwidth.OpenApiClient.Global.Subscriptions.Item.WithSubscriptionPatchResponse>(requestInfo, global::Soenneker.Bandwidth.OpenApiClient.Global.Subscriptions.Item.WithSubscriptionPatchResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Update Subscription
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bandwidth.OpenApiClient.Global.Subscriptions.Item.WithSubscriptionPutResponse"/></returns>
        /// <param name="body">Data representing a Subscription</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Bandwidth.OpenApiClient.Models.ResponseProperties_1">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Bandwidth.OpenApiClient.Models.ResponseProperties_1">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Bandwidth.OpenApiClient.Models.ResponseProperties_1">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Bandwidth.OpenApiClient.Models.ResponseProperties_1">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Bandwidth.OpenApiClient.Models.ResponseProperties_1">When receiving a 405 status code</exception>
        /// <exception cref="global::Soenneker.Bandwidth.OpenApiClient.Models.ResponseProperties_1">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Bandwidth.OpenApiClient.Global.Subscriptions.Item.WithSubscriptionPutResponse?> PutAsync(global::Soenneker.Bandwidth.OpenApiClient.Models.Subscription_1 body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Bandwidth.OpenApiClient.Global.Subscriptions.Item.WithSubscriptionPutResponse> PutAsync(global::Soenneker.Bandwidth.OpenApiClient.Models.Subscription_1 body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Bandwidth.OpenApiClient.Models.ResponseProperties_1.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Bandwidth.OpenApiClient.Models.ResponseProperties_1.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Bandwidth.OpenApiClient.Models.ResponseProperties_1.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Bandwidth.OpenApiClient.Models.ResponseProperties_1.CreateFromDiscriminatorValue },
                { "405", global::Soenneker.Bandwidth.OpenApiClient.Models.ResponseProperties_1.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Bandwidth.OpenApiClient.Models.ResponseProperties_1.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Bandwidth.OpenApiClient.Global.Subscriptions.Item.WithSubscriptionPutResponse>(requestInfo, global::Soenneker.Bandwidth.OpenApiClient.Global.Subscriptions.Item.WithSubscriptionPutResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Delete Subscription
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// GET Subscription by ID
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Modify Subscription
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">Modify Subscription Model</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPatchRequestInformation(global::Soenneker.Bandwidth.OpenApiClient.Models.ModifySubscription_1 body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPatchRequestInformation(global::Soenneker.Bandwidth.OpenApiClient.Models.ModifySubscription_1 body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PATCH, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Update Subscription
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">Data representing a Subscription</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPutRequestInformation(global::Soenneker.Bandwidth.OpenApiClient.Models.Subscription_1 body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPutRequestInformation(global::Soenneker.Bandwidth.OpenApiClient.Models.Subscription_1 body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PUT, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bandwidth.OpenApiClient.Global.Subscriptions.Item.WithSubscriptionItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Bandwidth.OpenApiClient.Global.Subscriptions.Item.WithSubscriptionItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Bandwidth.OpenApiClient.Global.Subscriptions.Item.WithSubscriptionItemRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
