// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Bandwidth.OpenApiClient.NumberManagement.Accounts.Item.Sites.Item.Sippeers.Item.Tns.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Bandwidth.OpenApiClient.NumberManagement.Accounts.Item.Sites.Item.Sippeers.Item.Tns
{
    /// <summary>
    /// Builds and executes requests for operations under \number-management\accounts\{accountId}\sites\{siteId}\sippeers\{sippeerId}\tns
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TnsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Bandwidth.OpenApiClient.numberManagement.accounts.item.sites.item.sippeers.item.tns.item collection</summary>
        /// <param name="position">A E.164 telephone number.</param>
        /// <returns>A <see cref="global::Soenneker.Bandwidth.OpenApiClient.NumberManagement.Accounts.Item.Sites.Item.Sippeers.Item.Tns.Item.WithTnItemRequestBuilder"/></returns>
        public global::Soenneker.Bandwidth.OpenApiClient.NumberManagement.Accounts.Item.Sites.Item.Sippeers.Item.Tns.Item.WithTnItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("tn", position);
                return new global::Soenneker.Bandwidth.OpenApiClient.NumberManagement.Accounts.Item.Sites.Item.Sippeers.Item.Tns.Item.WithTnItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bandwidth.OpenApiClient.NumberManagement.Accounts.Item.Sites.Item.Sippeers.Item.Tns.TnsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TnsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/number-management/accounts/{accountId}/sites/{siteId}/sippeers/{sippeerId}/tns", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bandwidth.OpenApiClient.NumberManagement.Accounts.Item.Sites.Item.Sippeers.Item.Tns.TnsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TnsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/number-management/accounts/{accountId}/sites/{siteId}/sippeers/{sippeerId}/tns", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
