// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Bandwidth.OpenApiClient.TollFreeVerification.Accounts;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Bandwidth.OpenApiClient.TollFreeVerification
{
    /// <summary>
    /// Builds and executes requests for operations under \toll-free-verification
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TollFreeVerificationRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The accounts property</summary>
        public global::Soenneker.Bandwidth.OpenApiClient.TollFreeVerification.Accounts.AccountsRequestBuilder Accounts
        {
            get => new global::Soenneker.Bandwidth.OpenApiClient.TollFreeVerification.Accounts.AccountsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tollFreeVerification property</summary>
        public global::Soenneker.Bandwidth.OpenApiClient.TollFreeVerification.TollFreeVerification.TollFreeVerificationRequestBuilder TollFreeVerification
        {
            get => new global::Soenneker.Bandwidth.OpenApiClient.TollFreeVerification.TollFreeVerification.TollFreeVerificationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bandwidth.OpenApiClient.TollFreeVerification.TollFreeVerificationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TollFreeVerificationRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/toll-free-verification", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bandwidth.OpenApiClient.TollFreeVerification.TollFreeVerificationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TollFreeVerificationRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/toll-free-verification", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
