// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Bandwidth.OpenApiClient.NumberManagement.Accounts.Item.NumberReputationManagement.PhoneNumbers.Stats
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class StatsGetResponse_data_carriersReputationSummaryCounts : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The number of phone numbers with the identity status &quot;CLEAN&quot;</summary>
        public int? CLEAN { get; set; }
        /// <summary>The number of phone numbers with the identity status &quot;REMEDIATION_DENIED&quot;</summary>
        public int? FLAGGED { get; set; }
        /// <summary>The number of phone numbers with the identity status &quot;REGISTRATION_IN_PROGRESS&quot;</summary>
        public int? STATUSPENDING { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bandwidth.OpenApiClient.NumberManagement.Accounts.Item.NumberReputationManagement.PhoneNumbers.Stats.StatsGetResponse_data_carriersReputationSummaryCounts"/> and sets the default values.
        /// </summary>
        public StatsGetResponse_data_carriersReputationSummaryCounts()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bandwidth.OpenApiClient.NumberManagement.Accounts.Item.NumberReputationManagement.PhoneNumbers.Stats.StatsGetResponse_data_carriersReputationSummaryCounts"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Bandwidth.OpenApiClient.NumberManagement.Accounts.Item.NumberReputationManagement.PhoneNumbers.Stats.StatsGetResponse_data_carriersReputationSummaryCounts CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Bandwidth.OpenApiClient.NumberManagement.Accounts.Item.NumberReputationManagement.PhoneNumbers.Stats.StatsGetResponse_data_carriersReputationSummaryCounts();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "CLEAN", n => { CLEAN = n.GetIntValue(); } },
                { "FLAGGED", n => { FLAGGED = n.GetIntValue(); } },
                { "STATUS_PENDING", n => { STATUSPENDING = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("CLEAN", CLEAN);
            writer.WriteIntValue("FLAGGED", FLAGGED);
            writer.WriteIntValue("STATUS_PENDING", STATUSPENDING);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
