// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Bandwidth.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Bandwidth.OpenApiClient.VoiceStirShaken.Accounts.Item.StirShakenCertificates.EncryptionKey
{
    /// <summary>
    /// Builds and executes requests for operations under \voice-stir-shaken\accounts\{accountId}\stirShakenCertificates\encryptionKey
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EncryptionKeyRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bandwidth.OpenApiClient.VoiceStirShaken.Accounts.Item.StirShakenCertificates.EncryptionKey.EncryptionKeyRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EncryptionKeyRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/voice-stir-shaken/accounts/{accountId}/stirShakenCertificates/encryptionKey", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bandwidth.OpenApiClient.VoiceStirShaken.Accounts.Item.StirShakenCertificates.EncryptionKey.EncryptionKeyRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EncryptionKeyRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/voice-stir-shaken/accounts/{accountId}/stirShakenCertificates/encryptionKey", rawUrl)
        {
        }
        /// <summary>
        /// Get the Certificate used for encrypting sensitive data.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bandwidth.OpenApiClient.VoiceStirShaken.Accounts.Item.StirShakenCertificates.EncryptionKey.EncryptionKeyGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Bandwidth.OpenApiClient.Models.VoiceStirShakenErrorResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Bandwidth.OpenApiClient.Models.VoiceStirShakenErrorResponse">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Bandwidth.OpenApiClient.Models.VoiceStirShakenErrorResponse">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Bandwidth.OpenApiClient.Models.VoiceStirShakenErrorResponse">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Bandwidth.OpenApiClient.Models.VoiceStirShakenErrorResponse">When receiving a 405 status code</exception>
        /// <exception cref="global::Soenneker.Bandwidth.OpenApiClient.Models.VoiceStirShakenErrorResponse">When receiving a 429 status code</exception>
        /// <exception cref="global::Soenneker.Bandwidth.OpenApiClient.Models.VoiceStirShakenErrorResponse">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Bandwidth.OpenApiClient.VoiceStirShaken.Accounts.Item.StirShakenCertificates.EncryptionKey.EncryptionKeyGetResponse?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Bandwidth.OpenApiClient.VoiceStirShaken.Accounts.Item.StirShakenCertificates.EncryptionKey.EncryptionKeyGetResponse> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Bandwidth.OpenApiClient.Models.VoiceStirShakenErrorResponse.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Bandwidth.OpenApiClient.Models.VoiceStirShakenErrorResponse.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Bandwidth.OpenApiClient.Models.VoiceStirShakenErrorResponse.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Bandwidth.OpenApiClient.Models.VoiceStirShakenErrorResponse.CreateFromDiscriminatorValue },
                { "405", global::Soenneker.Bandwidth.OpenApiClient.Models.VoiceStirShakenErrorResponse.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Bandwidth.OpenApiClient.Models.VoiceStirShakenErrorResponse.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Bandwidth.OpenApiClient.Models.VoiceStirShakenErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Bandwidth.OpenApiClient.VoiceStirShaken.Accounts.Item.StirShakenCertificates.EncryptionKey.EncryptionKeyGetResponse>(requestInfo, global::Soenneker.Bandwidth.OpenApiClient.VoiceStirShaken.Accounts.Item.StirShakenCertificates.EncryptionKey.EncryptionKeyGetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get the Certificate used for encrypting sensitive data.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bandwidth.OpenApiClient.VoiceStirShaken.Accounts.Item.StirShakenCertificates.EncryptionKey.EncryptionKeyRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Bandwidth.OpenApiClient.VoiceStirShaken.Accounts.Item.StirShakenCertificates.EncryptionKey.EncryptionKeyRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Bandwidth.OpenApiClient.VoiceStirShaken.Accounts.Item.StirShakenCertificates.EncryptionKey.EncryptionKeyRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
