// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Bandwidth.OpenApiClient.Global.Configuration.Voiceuri
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetVoiceUriProtocolQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "SIP")]
        #pragma warning disable CS1591
        SIP,
        #pragma warning restore CS1591
        [EnumMember(Value = "TEL")]
        #pragma warning disable CS1591
        TEL,
        #pragma warning restore CS1591
    }
}
