// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Bandwidth.OpenApiClient.PsapAlerts.Accounts.Item.Emergency.PsapAlerts.Incidents;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Bandwidth.OpenApiClient.PsapAlerts.Accounts.Item.Emergency.PsapAlerts
{
    /// <summary>
    /// Builds and executes requests for operations under \psap-alerts\accounts\{accountId}\emergency\psap-alerts
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PsapAlertsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The incidents property</summary>
        public global::Soenneker.Bandwidth.OpenApiClient.PsapAlerts.Accounts.Item.Emergency.PsapAlerts.Incidents.IncidentsRequestBuilder Incidents
        {
            get => new global::Soenneker.Bandwidth.OpenApiClient.PsapAlerts.Accounts.Item.Emergency.PsapAlerts.Incidents.IncidentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bandwidth.OpenApiClient.PsapAlerts.Accounts.Item.Emergency.PsapAlerts.PsapAlertsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PsapAlertsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/psap-alerts/accounts/{accountId}/emergency/psap-alerts", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bandwidth.OpenApiClient.PsapAlerts.Accounts.Item.Emergency.PsapAlerts.PsapAlertsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PsapAlertsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/psap-alerts/accounts/{accountId}/emergency/psap-alerts", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
