// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Bandwidth.OpenApiClient.Global.Inventory.Did
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetServiceTypeQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "VOX800")]
        #pragma warning disable CS1591
        VOX800,
        #pragma warning restore CS1591
        [EnumMember(Value = "VOXDID")]
        #pragma warning disable CS1591
        VOXDID,
        #pragma warning restore CS1591
    }
}
