// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Bandwidth.OpenApiClient.Messaging.Users.Item.Messages.MultiChannel;
using Soenneker.Bandwidth.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Bandwidth.OpenApiClient.Messaging.Users.Item.Messages
{
    /// <summary>
    /// Builds and executes requests for operations under \messaging\users\{accountId}\messages
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MessagesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The multiChannel property</summary>
        public global::Soenneker.Bandwidth.OpenApiClient.Messaging.Users.Item.Messages.MultiChannel.MultiChannelRequestBuilder MultiChannel
        {
            get => new global::Soenneker.Bandwidth.OpenApiClient.Messaging.Users.Item.Messages.MultiChannel.MultiChannelRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bandwidth.OpenApiClient.Messaging.Users.Item.Messages.MessagesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MessagesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/messaging/users/{accountId}/messages{?bwQueued*,calledNumberCountryA3*,callingNumberCountryA3*,campaignId*,carrierName*,carrierQueued*,destinationTn*,errorCode*,fromBwLatency*,fromCarrierLatency*,fromDateTime*,fromMessageSize*,fromSegmentCount*,limit*,limitTotalCount*,location*,messageDirection*,messageId*,messageStatus*,messageType*,pageToken*,product*,sort*,sourceTn*,toDateTime*,toMessageSize*,toSegmentCount*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bandwidth.OpenApiClient.Messaging.Users.Item.Messages.MessagesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MessagesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/messaging/users/{accountId}/messages{?bwQueued*,calledNumberCountryA3*,callingNumberCountryA3*,campaignId*,carrierName*,carrierQueued*,destinationTn*,errorCode*,fromBwLatency*,fromCarrierLatency*,fromDateTime*,fromMessageSize*,fromSegmentCount*,limit*,limitTotalCount*,location*,messageDirection*,messageId*,messageStatus*,messageType*,pageToken*,product*,sort*,sourceTn*,toDateTime*,toMessageSize*,toSegmentCount*}", rawUrl)
        {
        }
        /// <summary>
        /// Returns a list of messages based on query parameters.**Rate Limit:** This endpoint is rate limited to 3500 requests per 5 minutes per Source IP address. Exceeding the limit returns HTTP 429 with a `Retry-After` header.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bandwidth.OpenApiClient.Models.MessagesList"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Bandwidth.OpenApiClient.Models.MessagingRequestError">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Bandwidth.OpenApiClient.Models.MessagingRequestError">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Bandwidth.OpenApiClient.Models.MessagingRequestError">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Bandwidth.OpenApiClient.Models.MessagingRequestError">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Bandwidth.OpenApiClient.Models.MessagingRequestError">When receiving a 405 status code</exception>
        /// <exception cref="global::Soenneker.Bandwidth.OpenApiClient.Models.MessagingRequestError">When receiving a 415 status code</exception>
        /// <exception cref="global::Soenneker.Bandwidth.OpenApiClient.Models.MessagingRequestError">When receiving a 429 status code</exception>
        /// <exception cref="global::Soenneker.Bandwidth.OpenApiClient.Models.MessagingRequestError">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Bandwidth.OpenApiClient.Models.MessagesList?> GetAsync(Action<RequestConfiguration<global::Soenneker.Bandwidth.OpenApiClient.Messaging.Users.Item.Messages.MessagesRequestBuilder.MessagesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Bandwidth.OpenApiClient.Models.MessagesList> GetAsync(Action<RequestConfiguration<global::Soenneker.Bandwidth.OpenApiClient.Messaging.Users.Item.Messages.MessagesRequestBuilder.MessagesRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Bandwidth.OpenApiClient.Models.MessagingRequestError.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Bandwidth.OpenApiClient.Models.MessagingRequestError.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Bandwidth.OpenApiClient.Models.MessagingRequestError.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Bandwidth.OpenApiClient.Models.MessagingRequestError.CreateFromDiscriminatorValue },
                { "405", global::Soenneker.Bandwidth.OpenApiClient.Models.MessagingRequestError.CreateFromDiscriminatorValue },
                { "415", global::Soenneker.Bandwidth.OpenApiClient.Models.MessagingRequestError.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Bandwidth.OpenApiClient.Models.MessagingRequestError.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Bandwidth.OpenApiClient.Models.MessagingRequestError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Bandwidth.OpenApiClient.Models.MessagesList>(requestInfo, global::Soenneker.Bandwidth.OpenApiClient.Models.MessagesList.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Endpoint for sending text messages and picture messages using V2 messaging.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bandwidth.OpenApiClient.Models.Message"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Bandwidth.OpenApiClient.Models.CreateMessageRequestError">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Bandwidth.OpenApiClient.Models.MessagingRequestError">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Bandwidth.OpenApiClient.Models.MessagingRequestError">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Bandwidth.OpenApiClient.Models.MessagingRequestError">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Bandwidth.OpenApiClient.Models.MessagingRequestError">When receiving a 405 status code</exception>
        /// <exception cref="global::Soenneker.Bandwidth.OpenApiClient.Models.MessagingRequestError">When receiving a 406 status code</exception>
        /// <exception cref="global::Soenneker.Bandwidth.OpenApiClient.Models.MessagingRequestError">When receiving a 415 status code</exception>
        /// <exception cref="global::Soenneker.Bandwidth.OpenApiClient.Models.MessagingRequestError">When receiving a 429 status code</exception>
        /// <exception cref="global::Soenneker.Bandwidth.OpenApiClient.Models.MessagingRequestError">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Bandwidth.OpenApiClient.Models.Message?> PostAsync(global::Soenneker.Bandwidth.OpenApiClient.Models.MessageRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Bandwidth.OpenApiClient.Models.Message> PostAsync(global::Soenneker.Bandwidth.OpenApiClient.Models.MessageRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Bandwidth.OpenApiClient.Models.CreateMessageRequestError.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Bandwidth.OpenApiClient.Models.MessagingRequestError.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Bandwidth.OpenApiClient.Models.MessagingRequestError.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Bandwidth.OpenApiClient.Models.MessagingRequestError.CreateFromDiscriminatorValue },
                { "405", global::Soenneker.Bandwidth.OpenApiClient.Models.MessagingRequestError.CreateFromDiscriminatorValue },
                { "406", global::Soenneker.Bandwidth.OpenApiClient.Models.MessagingRequestError.CreateFromDiscriminatorValue },
                { "415", global::Soenneker.Bandwidth.OpenApiClient.Models.MessagingRequestError.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Bandwidth.OpenApiClient.Models.MessagingRequestError.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Bandwidth.OpenApiClient.Models.MessagingRequestError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Bandwidth.OpenApiClient.Models.Message>(requestInfo, global::Soenneker.Bandwidth.OpenApiClient.Models.Message.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns a list of messages based on query parameters.**Rate Limit:** This endpoint is rate limited to 3500 requests per 5 minutes per Source IP address. Exceeding the limit returns HTTP 429 with a `Retry-After` header.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Bandwidth.OpenApiClient.Messaging.Users.Item.Messages.MessagesRequestBuilder.MessagesRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Bandwidth.OpenApiClient.Messaging.Users.Item.Messages.MessagesRequestBuilder.MessagesRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Endpoint for sending text messages and picture messages using V2 messaging.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Bandwidth.OpenApiClient.Models.MessageRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Bandwidth.OpenApiClient.Models.MessageRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bandwidth.OpenApiClient.Messaging.Users.Item.Messages.MessagesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Bandwidth.OpenApiClient.Messaging.Users.Item.Messages.MessagesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Bandwidth.OpenApiClient.Messaging.Users.Item.Messages.MessagesRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Returns a list of messages based on query parameters.**Rate Limit:** This endpoint is rate limited to 3500 requests per 5 minutes per Source IP address. Exceeding the limit returns HTTP 429 with a `Retry-After` header.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class MessagesRequestBuilderGetQueryParameters 
        {
            /// <summary>A boolean value indicating whether the message is queued in the Bandwidth network.</summary>
            [QueryParameter("bwQueued")]
            public bool? BwQueued { get; set; }
            /// <summary>Called number country in A3 format.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("calledNumberCountryA3")]
            public string? CalledNumberCountryA3 { get; set; }
#nullable restore
#else
            [QueryParameter("calledNumberCountryA3")]
            public string CalledNumberCountryA3 { get; set; }
#endif
            /// <summary>Calling number country in A3 format.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("callingNumberCountryA3")]
            public string? CallingNumberCountryA3 { get; set; }
#nullable restore
#else
            [QueryParameter("callingNumberCountryA3")]
            public string CallingNumberCountryA3 { get; set; }
#endif
            /// <summary>The campaign ID of the message.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("campaignId")]
            public string? CampaignId { get; set; }
#nullable restore
#else
            [QueryParameter("campaignId")]
            public string CampaignId { get; set; }
#endif
            /// <summary>The name of the carrier used for this message. Possible values include but are not limited to Verizon and TMobile. Special characters need to be encoded using URL encoding (i.e. AT&amp;T should be passed as AT%26T).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("carrierName")]
            public string? CarrierName { get; set; }
#nullable restore
#else
            [QueryParameter("carrierName")]
            public string CarrierName { get; set; }
#endif
            /// <summary>A boolean value indicating whether the message is queued in the carrier network. Only available for OUTBOUND messages from accounts with the Advanced Quality Metrics feature enabled.</summary>
            [QueryParameter("carrierQueued")]
            public bool? CarrierQueued { get; set; }
            /// <summary>&quot;The phone number that received the message. Accepted values are: a single full phone number a comma separated list of full phone numbers (maximum of 10) or a single partial phone number (minimum of 5 characters e.g. &apos;%2B1919&apos;).&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("destinationTn")]
            public string? DestinationTn { get; set; }
#nullable restore
#else
            [QueryParameter("destinationTn")]
            public string DestinationTn { get; set; }
#endif
            /// <summary>The error code of the message.</summary>
            [QueryParameter("errorCode")]
            public int? ErrorCode { get; set; }
            /// <summary>The minimum Bandwidth latency of the message in seconds. Only available for accounts with the Advanced Quality Metrics feature enabled.</summary>
            [QueryParameter("fromBwLatency")]
            public int? FromBwLatency { get; set; }
            /// <summary>The minimum carrier latency of the message in seconds. Only available for OUTBOUND messages from accounts with the Advanced Quality Metrics feature enabled.</summary>
            [QueryParameter("fromCarrierLatency")]
            public int? FromCarrierLatency { get; set; }
            /// <summary>The start of the date range to search in ISO 8601 format. Uses the message receive time. The date range to search in is currently 14 days.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("fromDateTime")]
            public string? FromDateTime { get; set; }
#nullable restore
#else
            [QueryParameter("fromDateTime")]
            public string FromDateTime { get; set; }
#endif
            /// <summary>Message size (start range).</summary>
            [QueryParameter("fromMessageSize")]
            public int? FromMessageSize { get; set; }
            /// <summary>Segment count (start range).</summary>
            [QueryParameter("fromSegmentCount")]
            public int? FromSegmentCount { get; set; }
            /// <summary>The maximum records requested in search result. Default 100. The sum of limit and after cannot be more than 10000.</summary>
            [QueryParameter("limit")]
            public int? Limit { get; set; }
            /// <summary>When set to true, the response&apos;s totalCount field will have a maximum value of 10,000. When set to false, or excluded, this will give an accurate totalCount of all messages that match the provided filters. If you are experiencing latency, try using this parameter to limit your results.</summary>
            [QueryParameter("limitTotalCount")]
            public bool? LimitTotalCount { get; set; }
            /// <summary>Location Id associated with the message.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("location")]
            public string? Location { get; set; }
#nullable restore
#else
            [QueryParameter("location")]
            public string Location { get; set; }
#endif
            /// <summary>The direction of the message. One of INBOUND OUTBOUND.</summary>
            [Obsolete("This property is deprecated, use MessageDirectionAsListMessageDirectionEnum instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("messageDirection")]
            public string? MessageDirection { get; set; }
#nullable restore
#else
            [QueryParameter("messageDirection")]
            public string MessageDirection { get; set; }
#endif
            /// <summary>The direction of the message. One of INBOUND OUTBOUND.</summary>
            [QueryParameter("messageDirection")]
            public global::Soenneker.Bandwidth.OpenApiClient.Models.ListMessageDirectionEnum? MessageDirectionAsListMessageDirectionEnum { get; set; }
            /// <summary>The ID of the message to search for. Special characters need to be encoded using URL encoding. Message IDs could come in different formats, e.g., 9e0df4ca-b18d-40d7-a59f-82fcdf5ae8e6 and 1589228074636lm4k2je7j7jklbn2 are valid message ID formats. Note that you must include at least one query parameter.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("messageId")]
            public string? MessageId { get; set; }
#nullable restore
#else
            [QueryParameter("messageId")]
            public string MessageId { get; set; }
#endif
            /// <summary>The status of the message. One of RECEIVED QUEUED SENDING SENT FAILED DELIVERED ACCEPTED UNDELIVERED.</summary>
            [Obsolete("This property is deprecated, use MessageStatusAsMessageStatusEnum instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("messageStatus")]
            public string? MessageStatus { get; set; }
#nullable restore
#else
            [QueryParameter("messageStatus")]
            public string MessageStatus { get; set; }
#endif
            /// <summary>The status of the message. One of RECEIVED QUEUED SENDING SENT FAILED DELIVERED ACCEPTED UNDELIVERED.</summary>
            [QueryParameter("messageStatus")]
            public global::Soenneker.Bandwidth.OpenApiClient.Models.MessageStatusEnum? MessageStatusAsMessageStatusEnum { get; set; }
            /// <summary>The type of message. Either sms or mms.</summary>
            [Obsolete("This property is deprecated, use MessageTypeAsMessageTypeEnum instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("messageType")]
            public string? MessageType { get; set; }
#nullable restore
#else
            [QueryParameter("messageType")]
            public string MessageType { get; set; }
#endif
            /// <summary>The type of message. Either sms or mms.</summary>
            [QueryParameter("messageType")]
            public global::Soenneker.Bandwidth.OpenApiClient.Models.MessageTypeEnum? MessageTypeAsMessageTypeEnum { get; set; }
            /// <summary>A base64 encoded value used for pagination of results.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("pageToken")]
            public string? PageToken { get; set; }
#nullable restore
#else
            [QueryParameter("pageToken")]
            public string PageToken { get; set; }
#endif
            /// <summary>Messaging product associated with the message.</summary>
            [Obsolete("This property is deprecated, use ProductAsProductTypeEnum instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("product")]
            public string? Product { get; set; }
#nullable restore
#else
            [QueryParameter("product")]
            public string Product { get; set; }
#endif
            /// <summary>Messaging product associated with the message.</summary>
            [QueryParameter("product")]
            public global::Soenneker.Bandwidth.OpenApiClient.Models.ProductTypeEnum? ProductAsProductTypeEnum { get; set; }
            /// <summary>The field and direction to sort by combined with a colon. Direction is either asc or desc.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("sort")]
            public string? Sort { get; set; }
#nullable restore
#else
            [QueryParameter("sort")]
            public string Sort { get; set; }
#endif
            /// <summary>&quot;The phone number that sent the message. Accepted values are: a single full phone number a comma separated list of full phone numbers (maximum of 10) or a single partial phone number (minimum of 5 characters e.g. &apos;%2B1919&apos;).&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("sourceTn")]
            public string? SourceTn { get; set; }
#nullable restore
#else
            [QueryParameter("sourceTn")]
            public string SourceTn { get; set; }
#endif
            /// <summary>The end of the date range to search in ISO 8601 format. Uses the message receive time. The date range to search in is currently 14 days.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("toDateTime")]
            public string? ToDateTime { get; set; }
#nullable restore
#else
            [QueryParameter("toDateTime")]
            public string ToDateTime { get; set; }
#endif
            /// <summary>Message size (end range).</summary>
            [QueryParameter("toMessageSize")]
            public int? ToMessageSize { get; set; }
            /// <summary>Segment count (end range).</summary>
            [QueryParameter("toSegmentCount")]
            public int? ToSegmentCount { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class MessagesRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Soenneker.Bandwidth.OpenApiClient.Messaging.Users.Item.Messages.MessagesRequestBuilder.MessagesRequestBuilderGetQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class MessagesRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
