// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Bandwidth.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Bandwidth.OpenApiClient.Models.AddressResponseAssetData"/>, <see cref="global::Soenneker.Bandwidth.OpenApiClient.Models.ComplianceDocumentResponseData"/>, <see cref="global::Soenneker.Bandwidth.OpenApiClient.Models.EndUserResponseAssetData"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AssetGetDataAssetReferenceData : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Bandwidth.OpenApiClient.Models.AddressResponseAssetData"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bandwidth.OpenApiClient.Models.AddressResponseAssetData? AddressResponseAssetData { get; set; }
#nullable restore
#else
        public global::Soenneker.Bandwidth.OpenApiClient.Models.AddressResponseAssetData AddressResponseAssetData { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Bandwidth.OpenApiClient.Models.ComplianceDocumentResponseData"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bandwidth.OpenApiClient.Models.ComplianceDocumentResponseData? ComplianceDocumentResponseData { get; set; }
#nullable restore
#else
        public global::Soenneker.Bandwidth.OpenApiClient.Models.ComplianceDocumentResponseData ComplianceDocumentResponseData { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Bandwidth.OpenApiClient.Models.EndUserResponseAssetData"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bandwidth.OpenApiClient.Models.EndUserResponseAssetData? EndUserResponseAssetData { get; set; }
#nullable restore
#else
        public global::Soenneker.Bandwidth.OpenApiClient.Models.EndUserResponseAssetData EndUserResponseAssetData { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bandwidth.OpenApiClient.Models.AssetGetDataAssetReferenceData"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Bandwidth.OpenApiClient.Models.AssetGetDataAssetReferenceData CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
            var result = new global::Soenneker.Bandwidth.OpenApiClient.Models.AssetGetDataAssetReferenceData();
            if("AddressResponseAssetData".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.AddressResponseAssetData = new global::Soenneker.Bandwidth.OpenApiClient.Models.AddressResponseAssetData();
            }
            else if("ComplianceDocumentResponseData".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ComplianceDocumentResponseData = new global::Soenneker.Bandwidth.OpenApiClient.Models.ComplianceDocumentResponseData();
            }
            else if("EndUserResponseAssetData".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.EndUserResponseAssetData = new global::Soenneker.Bandwidth.OpenApiClient.Models.EndUserResponseAssetData();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(AddressResponseAssetData != null)
            {
                return AddressResponseAssetData.GetFieldDeserializers();
            }
            else if(ComplianceDocumentResponseData != null)
            {
                return ComplianceDocumentResponseData.GetFieldDeserializers();
            }
            else if(EndUserResponseAssetData != null)
            {
                return EndUserResponseAssetData.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(AddressResponseAssetData != null)
            {
                writer.WriteObjectValue<global::Soenneker.Bandwidth.OpenApiClient.Models.AddressResponseAssetData>(null, AddressResponseAssetData);
            }
            else if(ComplianceDocumentResponseData != null)
            {
                writer.WriteObjectValue<global::Soenneker.Bandwidth.OpenApiClient.Models.ComplianceDocumentResponseData>(null, ComplianceDocumentResponseData);
            }
            else if(EndUserResponseAssetData != null)
            {
                writer.WriteObjectValue<global::Soenneker.Bandwidth.OpenApiClient.Models.EndUserResponseAssetData>(null, EndUserResponseAssetData);
            }
        }
    }
}
#pragma warning restore CS0618
