// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Bandwidth.OpenApiClient.Models
{
    /// <summary>Attestation level. A (Full), B (Partial), or C (Gateway). Required for US/CAN hosted signing cert assignments. For FR hosted assignments, this can be null as the &apos;indirect&apos; profileType will dictate the attestLevel.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AttestLevel_1
    {
        [EnumMember(Value = "A")]
        #pragma warning disable CS1591
        A,
        #pragma warning restore CS1591
        [EnumMember(Value = "B")]
        #pragma warning disable CS1591
        B,
        #pragma warning restore CS1591
        [EnumMember(Value = "C")]
        #pragma warning disable CS1591
        C,
        #pragma warning restore CS1591
    }
}
