// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Bandwidth.OpenApiClient.Models
{
    /// <summary>The action to take on the phone numbers.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum BulkTnActionEnum
    {
        [EnumMember(Value = "ADD")]
        #pragma warning disable CS1591
        Add,
        #pragma warning restore CS1591
    }
}
