// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Bandwidth.OpenApiClient.Models
{
    /// <summary>The format can be RAW, E164, LOCALIZED and CLI_NONE. In case the format is E164 or LOCALIZED, then there should be a cliValue.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CallerId_cliFormat
    {
        [EnumMember(Value = "RAW")]
        #pragma warning disable CS1591
        RAW,
        #pragma warning restore CS1591
        [EnumMember(Value = "E164")]
        #pragma warning disable CS1591
        E164,
        #pragma warning restore CS1591
        [EnumMember(Value = "LOCALIZED")]
        #pragma warning disable CS1591
        LOCALIZED,
        #pragma warning restore CS1591
        [EnumMember(Value = "CLI_NONE")]
        #pragma warning disable CS1591
        CLI_NONE,
        #pragma warning restore CS1591
    }
}
