// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Bandwidth.OpenApiClient.Models
{
    /// <summary>The detected language for this transcription.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CallTranscriptionDetectedLanguageEnum
    {
        [EnumMember(Value = "en-US")]
        #pragma warning disable CS1591
        EnUS,
        #pragma warning restore CS1591
        [EnumMember(Value = "es-US")]
        #pragma warning disable CS1591
        EsUS,
        #pragma warning restore CS1591
        [EnumMember(Value = "fr-FR")]
        #pragma warning disable CS1591
        FrFR,
        #pragma warning restore CS1591
    }
}
