// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Bandwidth.OpenApiClient.Models
{
    /// <summary>The status of the short code campaign.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CampaignStatus
    {
        [EnumMember(Value = "PENDING_USE_CASE_REVIEW")]
        #pragma warning disable CS1591
        PendingUseCaseReview,
        #pragma warning restore CS1591
        [EnumMember(Value = "PENDING_BW_REVIEW")]
        #pragma warning disable CS1591
        PendingBwReview,
        #pragma warning restore CS1591
        [EnumMember(Value = "PROVISIONING_SHORTCODE")]
        #pragma warning disable CS1591
        ProvisioningShortcode,
        #pragma warning restore CS1591
        [EnumMember(Value = "ACTION_REQUIRED")]
        #pragma warning disable CS1591
        ActionRequired,
        #pragma warning restore CS1591
        [EnumMember(Value = "PENDING_CARRIER_REVIEW")]
        #pragma warning disable CS1591
        PendingCarrierReview,
        #pragma warning restore CS1591
        [EnumMember(Value = "APPROVED")]
        #pragma warning disable CS1591
        Approved,
        #pragma warning restore CS1591
        [EnumMember(Value = "DENIED")]
        #pragma warning disable CS1591
        Denied,
        #pragma warning restore CS1591
        [EnumMember(Value = "ABANDONED")]
        #pragma warning disable CS1591
        Abandoned,
        #pragma warning restore CS1591
        [EnumMember(Value = "DELETED")]
        #pragma warning disable CS1591
        Deleted,
        #pragma warning restore CS1591
    }
}
