// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Bandwidth.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Category
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "CHARGES")]
        #pragma warning disable CS1591
        CHARGES,
        #pragma warning restore CS1591
        [EnumMember(Value = "NUMBER_DETAILS")]
        #pragma warning disable CS1591
        NUMBER_DETAILS,
        #pragma warning restore CS1591
        [EnumMember(Value = "USAGE")]
        #pragma warning disable CS1591
        USAGE,
        #pragma warning restore CS1591
    }
}
