// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Bandwidth.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreateCallResponse_1 : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The bandwidth account ID associated with the call.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccountId { get; set; }
#nullable restore
#else
        public string AccountId { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The HTTP method to use to deliver the callback. GET or POST. Default value is POST.</summary>
        public global::Soenneker.Bandwidth.OpenApiClient.Models.CallbackMethodEnum_1? AnswerFallbackMethod { get; set; }
        /// <summary>Fallback URL to deliver the `answer` event webhook.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AnswerFallbackUrl { get; set; }
#nullable restore
#else
        public string AnswerFallbackUrl { get; set; }
#endif
        /// <summary>The HTTP method to use to deliver the callback. GET or POST. Default value is POST.</summary>
        public global::Soenneker.Bandwidth.OpenApiClient.Models.CallbackMethodEnum_1? AnswerMethod { get; set; }
        /// <summary>URL to deliver the `answer` event webhook.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AnswerUrl { get; set; }
#nullable restore
#else
        public string AnswerUrl { get; set; }
#endif
        /// <summary>The id of the application associated with the `from` number.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ApplicationId { get; set; }
#nullable restore
#else
        public string ApplicationId { get; set; }
#endif
        /// <summary>This is the timeout (in seconds) to use when delivering webhooks for the call.</summary>
        public double? CallbackTimeout { get; set; }
        /// <summary>Programmable Voice API Call ID.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CallId { get; set; }
#nullable restore
#else
        public string CallId { get; set; }
#endif
        /// <summary>The timeout (in seconds) for the callee to answer the call after it starts ringing.</summary>
        public double? CallTimeout { get; set; }
        /// <summary>The URL to update this call&apos;s state.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CallUrl { get; set; }
#nullable restore
#else
        public string CallUrl { get; set; }
#endif
        /// <summary>The HTTP method to use to deliver the callback. GET or POST. Default value is POST.</summary>
        public global::Soenneker.Bandwidth.OpenApiClient.Models.CallbackMethodEnum_1? DisconnectMethod { get; set; }
        /// <summary>URL to deliver the `disconnect` event webhook.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisconnectUrl { get; set; }
#nullable restore
#else
        public string DisconnectUrl { get; set; }
#endif
        /// <summary>The time at which the call was accepted into the queue.</summary>
        public DateTimeOffset? EnqueuedTime { get; set; }
        /// <summary>Basic auth password.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FallbackPassword { get; set; }
#nullable restore
#else
        public string FallbackPassword { get; set; }
#endif
        /// <summary>Basic auth username.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FallbackUsername { get; set; }
#nullable restore
#else
        public string FallbackUsername { get; set; }
#endif
        /// <summary>Phone number that created the outbound call.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? From { get; set; }
#nullable restore
#else
        public string From { get; set; }
#endif
        /// <summary>Basic auth password.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Password { get; set; }
#nullable restore
#else
        public string Password { get; set; }
#endif
        /// <summary>The priority of this call over other calls from your account.</summary>
        public int? Priority { get; set; }
        /// <summary>Custom tag value.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Tag { get; set; }
#nullable restore
#else
        public string Tag { get; set; }
#endif
        /// <summary>Recipient of the outgoing call.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? To { get; set; }
#nullable restore
#else
        public string To { get; set; }
#endif
        /// <summary>Basic auth username.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Username { get; set; }
#nullable restore
#else
        public string Username { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bandwidth.OpenApiClient.Models.CreateCallResponse_1"/> and sets the default values.
        /// </summary>
        public CreateCallResponse_1()
        {
            AdditionalData = new Dictionary<string, object>();
            AnswerFallbackMethod = global::Soenneker.Bandwidth.OpenApiClient.Models.CallbackMethodEnum_1.POST;
            AnswerMethod = global::Soenneker.Bandwidth.OpenApiClient.Models.CallbackMethodEnum_1.POST;
            DisconnectMethod = global::Soenneker.Bandwidth.OpenApiClient.Models.CallbackMethodEnum_1.POST;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bandwidth.OpenApiClient.Models.CreateCallResponse_1"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Bandwidth.OpenApiClient.Models.CreateCallResponse_1 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Bandwidth.OpenApiClient.Models.CreateCallResponse_1();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "accountId", n => { AccountId = n.GetStringValue(); } },
                { "answerFallbackMethod", n => { AnswerFallbackMethod = n.GetEnumValue<global::Soenneker.Bandwidth.OpenApiClient.Models.CallbackMethodEnum_1>(); } },
                { "answerFallbackUrl", n => { AnswerFallbackUrl = n.GetStringValue(); } },
                { "answerMethod", n => { AnswerMethod = n.GetEnumValue<global::Soenneker.Bandwidth.OpenApiClient.Models.CallbackMethodEnum_1>(); } },
                { "answerUrl", n => { AnswerUrl = n.GetStringValue(); } },
                { "applicationId", n => { ApplicationId = n.GetStringValue(); } },
                { "callId", n => { CallId = n.GetStringValue(); } },
                { "callTimeout", n => { CallTimeout = n.GetDoubleValue(); } },
                { "callUrl", n => { CallUrl = n.GetStringValue(); } },
                { "callbackTimeout", n => { CallbackTimeout = n.GetDoubleValue(); } },
                { "disconnectMethod", n => { DisconnectMethod = n.GetEnumValue<global::Soenneker.Bandwidth.OpenApiClient.Models.CallbackMethodEnum_1>(); } },
                { "disconnectUrl", n => { DisconnectUrl = n.GetStringValue(); } },
                { "enqueuedTime", n => { EnqueuedTime = n.GetDateTimeOffsetValue(); } },
                { "fallbackPassword", n => { FallbackPassword = n.GetStringValue(); } },
                { "fallbackUsername", n => { FallbackUsername = n.GetStringValue(); } },
                { "from", n => { From = n.GetStringValue(); } },
                { "password", n => { Password = n.GetStringValue(); } },
                { "priority", n => { Priority = n.GetIntValue(); } },
                { "tag", n => { Tag = n.GetStringValue(); } },
                { "to", n => { To = n.GetStringValue(); } },
                { "username", n => { Username = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("accountId", AccountId);
            writer.WriteEnumValue<global::Soenneker.Bandwidth.OpenApiClient.Models.CallbackMethodEnum_1>("answerFallbackMethod", AnswerFallbackMethod);
            writer.WriteStringValue("answerFallbackUrl", AnswerFallbackUrl);
            writer.WriteEnumValue<global::Soenneker.Bandwidth.OpenApiClient.Models.CallbackMethodEnum_1>("answerMethod", AnswerMethod);
            writer.WriteStringValue("answerUrl", AnswerUrl);
            writer.WriteStringValue("applicationId", ApplicationId);
            writer.WriteDoubleValue("callbackTimeout", CallbackTimeout);
            writer.WriteStringValue("callId", CallId);
            writer.WriteDoubleValue("callTimeout", CallTimeout);
            writer.WriteStringValue("callUrl", CallUrl);
            writer.WriteEnumValue<global::Soenneker.Bandwidth.OpenApiClient.Models.CallbackMethodEnum_1>("disconnectMethod", DisconnectMethod);
            writer.WriteStringValue("disconnectUrl", DisconnectUrl);
            writer.WriteDateTimeOffsetValue("enqueuedTime", EnqueuedTime);
            writer.WriteStringValue("fallbackPassword", FallbackPassword);
            writer.WriteStringValue("fallbackUsername", FallbackUsername);
            writer.WriteStringValue("from", From);
            writer.WriteStringValue("password", Password);
            writer.WriteIntValue("priority", Priority);
            writer.WriteStringValue("tag", Tag);
            writer.WriteStringValue("to", To);
            writer.WriteStringValue("username", Username);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
