// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Bandwidth.OpenApiClient.Models
{
    /// <summary>Residential or Business</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CustomerType
    {
        [EnumMember(Value = "RES")]
        #pragma warning disable CS1591
        RES,
        #pragma warning restore CS1591
        [EnumMember(Value = "BUS")]
        #pragma warning disable CS1591
        BUS,
        #pragma warning restore CS1591
    }
}
