// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Bandwidth.OpenApiClient.Models
{
    /// <summary>Status of a document - any new uploaded document will be marked as PENDING_VALIDATION and will need to be validated by our porting team.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum DocumentStatusTypeEnum
    {
        [EnumMember(Value = "PENDING_VALIDATION")]
        #pragma warning disable CS1591
        PENDING_VALIDATION,
        #pragma warning restore CS1591
        [EnumMember(Value = "VALID")]
        #pragma warning disable CS1591
        VALID,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID")]
        #pragma warning disable CS1591
        INVALID,
        #pragma warning restore CS1591
    }
}
