// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Bandwidth.OpenApiClient.Models
{
    /// <summary>The intent of a campaign nudge request. Which action is awaiting review?</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum EnumNudgeIntent
    {
        [EnumMember(Value = "APPEAL_REJECTION")]
        #pragma warning disable CS1591
        AppealRejection,
        #pragma warning restore CS1591
        [EnumMember(Value = "REVIEW")]
        #pragma warning disable CS1591
        Review,
        #pragma warning restore CS1591
    }
}
