// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Bandwidth.OpenApiClient.Models
{
    /// <summary>Political committee Locale. Possible values are federal, state, local and tribal.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum EnumPoliticalCommitteeLocale
    {
        [EnumMember(Value = "FEDERAL")]
        #pragma warning disable CS1591
        FEDERAL,
        #pragma warning restore CS1591
        [EnumMember(Value = "STATE")]
        #pragma warning disable CS1591
        STATE,
        #pragma warning restore CS1591
        [EnumMember(Value = "LOCAL")]
        #pragma warning disable CS1591
        LOCAL,
        #pragma warning restore CS1591
        [EnumMember(Value = "TRIBAL")]
        #pragma warning disable CS1591
        TRIBAL,
        #pragma warning restore CS1591
    }
}
