// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Bandwidth.OpenApiClient.Models
{
    /// <summary>Spain / Mobile / DNI, NIE, NIF, PASSPORT. Only required for personal addresses (salutation is either MR or MS).</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ExtraFields_idType
    {
        [EnumMember(Value = "DNI")]
        #pragma warning disable CS1591
        DNI,
        #pragma warning restore CS1591
        [EnumMember(Value = "NIF")]
        #pragma warning disable CS1591
        NIF,
        #pragma warning restore CS1591
        [EnumMember(Value = "NIE")]
        #pragma warning disable CS1591
        NIE,
        #pragma warning restore CS1591
        [EnumMember(Value = "PASSPORT")]
        #pragma warning disable CS1591
        PASSPORT,
        #pragma warning restore CS1591
    }
}
