// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Bandwidth.OpenApiClient.Models
{
    /// <summary>A unique identifier for feature.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum FeatureNameEnum_1
    {
        [EnumMember(Value = "REQUIREMENTS_PACKAGE")]
        #pragma warning disable CS1591
        REQUIREMENTS_PACKAGE,
        #pragma warning restore CS1591
        [EnumMember(Value = "EMERGENCY")]
        #pragma warning disable CS1591
        EMERGENCY,
        #pragma warning restore CS1591
        [EnumMember(Value = "PORTING")]
        #pragma warning disable CS1591
        PORTING,
        #pragma warning restore CS1591
    }
}
