// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Bandwidth.OpenApiClient.Models
{
    /// <summary>&quot;The geo validation status of the address.- `GEO_VALID`: The address is valid and geo validated.- `NOT_GEO_VALID`: The address is not valid or geo validated.- `NOT_GEO_VALIDATED`: The address has not been geo validated yet.&quot;</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GeoValidationStatusEnum_1
    {
        [EnumMember(Value = "GEO_VALID")]
        #pragma warning disable CS1591
        GEO_VALID,
        #pragma warning restore CS1591
        [EnumMember(Value = "NOT_GEO_VALID")]
        #pragma warning disable CS1591
        NOT_GEO_VALID,
        #pragma warning restore CS1591
        [EnumMember(Value = "NOT_GEO_VALIDATED")]
        #pragma warning disable CS1591
        NOT_GEO_VALIDATED,
        #pragma warning restore CS1591
    }
}
