// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Bandwidth.OpenApiClient.Models
{
    /// <summary>
    /// Create a new PSAP Outage Alert Incident
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class IncidentRequest : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The areas affected by the outage. This can be either a list of FCC IDs, two-letter state codes, or USA if the outage is nationwide.Once an alert has been triggered, the areas affected cannot be updated. In the case that additional areas are impacted after an alerthas been triggered, a new incident should be created with the additional areas affected.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? AreasAffected { get; set; }
#nullable restore
#else
        public List<string> AreasAffected { get; set; }
#endif
        /// <summary>The best known cause of the outage. If left blank, the PSAP will be notified that the cause of the outage is unknown.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CauseOfOutage { get; set; }
#nullable restore
#else
        public string CauseOfOutage { get; set; }
#endif
        /// <summary>The expected time the outage will be resolved. This will be shared with the PSAPs. If left blank, the PSAP will be notified that the expected restoration time is unknown.</summary>
        public DateTimeOffset? ExpectedRestorationTime { get; set; }
        /// <summary>A unique numeric identifier for the incident.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IncidentId { get; set; }
#nullable restore
#else
        public string IncidentId { get; set; }
#endif
        /// <summary>The time the incident occurred. This information is included in the initial alert that is sent to the PSAPs.This time cannot be updated after the alert has been triggered. This must be provided in UTC.</summary>
        public DateTimeOffset? IncidentStartTime { get; set; }
        /// <summary>&quot;The impact of the outage. This will be shared with the PSAPs to help them understand the impact of the outage.- CALL_COMPLETION: Users may be unable to complete 911 calls- CALL_QUALITY: Operators may experience call quality issues- CALL_QUALITY_AND_LOCATION_INFORMATION: Operators may experience call quality issues and loss of location information- LOCATION_INFORMATION: Operators may experience loss of location information&quot;</summary>
        public global::Soenneker.Bandwidth.OpenApiClient.Models.OutageImpact? OutageImpact { get; set; }
        /// <summary>Indicates if this alert should be created as a test alert. If true, the alert will only be able to be triggered as a test alert.Test alerts are not sent to the PSAPs, but instead are sent to the pre-configured test phone number and email address from the PSAP Outage Alert Settings.</summary>
        public bool? TestAlert { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bandwidth.OpenApiClient.Models.IncidentRequest"/> and sets the default values.
        /// </summary>
        public IncidentRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bandwidth.OpenApiClient.Models.IncidentRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Bandwidth.OpenApiClient.Models.IncidentRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Bandwidth.OpenApiClient.Models.IncidentRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "areasAffected", n => { AreasAffected = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "causeOfOutage", n => { CauseOfOutage = n.GetStringValue(); } },
                { "expectedRestorationTime", n => { ExpectedRestorationTime = n.GetDateTimeOffsetValue(); } },
                { "incidentId", n => { IncidentId = n.GetStringValue(); } },
                { "incidentStartTime", n => { IncidentStartTime = n.GetDateTimeOffsetValue(); } },
                { "outageImpact", n => { OutageImpact = n.GetEnumValue<global::Soenneker.Bandwidth.OpenApiClient.Models.OutageImpact>(); } },
                { "testAlert", n => { TestAlert = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("areasAffected", AreasAffected);
            writer.WriteStringValue("causeOfOutage", CauseOfOutage);
            writer.WriteDateTimeOffsetValue("expectedRestorationTime", ExpectedRestorationTime);
            writer.WriteStringValue("incidentId", IncidentId);
            writer.WriteDateTimeOffsetValue("incidentStartTime", IncidentStartTime);
            writer.WriteEnumValue<global::Soenneker.Bandwidth.OpenApiClient.Models.OutageImpact>("outageImpact", OutageImpact);
            writer.WriteBoolValue("testAlert", TestAlert);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
