// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Bandwidth.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum JsonWarning_1_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "SMS")]
        #pragma warning disable CS1591
        SMS,
        #pragma warning restore CS1591
        [EnumMember(Value = "E911")]
        #pragma warning disable CS1591
        E911,
        #pragma warning restore CS1591
    }
}
