// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Bandwidth.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class JsonDldaOrderResponsePayload_1 : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The accountId property</summary>
        public int? AccountId { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The createdByUser property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedByUser { get; set; }
#nullable restore
#else
        public string CreatedByUser { get; set; }
#endif
        /// <summary>The Customer Order ID is an ID assigned by the account owner to provide a reference number for the Order. Only alphanumeric values, dashes and spaces are allowed.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomerOrderId { get; set; }
#nullable restore
#else
        public string CustomerOrderId { get; set; }
#endif
        /// <summary>The dldaPhoneNumberGroups property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Bandwidth.OpenApiClient.Models.JsonDldaPhoneNumberGroup_1>? DldaPhoneNumberGroups { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Bandwidth.OpenApiClient.Models.JsonDldaPhoneNumberGroup_1> DldaPhoneNumberGroups { get; set; }
#endif
        /// <summary>The errors property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Bandwidth.OpenApiClient.Models.JsonDldaOrderResponsePayload_1_errors>? Errors { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Bandwidth.OpenApiClient.Models.JsonDldaOrderResponsePayload_1_errors> Errors { get; set; }
#endif
        /// <summary>The lastModifiedDate property</summary>
        public DateTimeOffset? LastModifiedDate { get; set; }
        /// <summary>The orderCreateDate property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrderCreateDate { get; set; }
#nullable restore
#else
        public string OrderCreateDate { get; set; }
#endif
        /// <summary>The orderId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrderId { get; set; }
#nullable restore
#else
        public string OrderId { get; set; }
#endif
        /// <summary>Order status.</summary>
        public global::Soenneker.Bandwidth.OpenApiClient.Models.JsonDldaOrderResponsePayload_1_processingStatus? ProcessingStatus { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bandwidth.OpenApiClient.Models.JsonDldaOrderResponsePayload_1"/> and sets the default values.
        /// </summary>
        public JsonDldaOrderResponsePayload_1()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bandwidth.OpenApiClient.Models.JsonDldaOrderResponsePayload_1"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Bandwidth.OpenApiClient.Models.JsonDldaOrderResponsePayload_1 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Bandwidth.OpenApiClient.Models.JsonDldaOrderResponsePayload_1();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "accountId", n => { AccountId = n.GetIntValue(); } },
                { "createdByUser", n => { CreatedByUser = n.GetStringValue(); } },
                { "customerOrderId", n => { CustomerOrderId = n.GetStringValue(); } },
                { "dldaPhoneNumberGroups", n => { DldaPhoneNumberGroups = n.GetCollectionOfObjectValues<global::Soenneker.Bandwidth.OpenApiClient.Models.JsonDldaPhoneNumberGroup_1>(global::Soenneker.Bandwidth.OpenApiClient.Models.JsonDldaPhoneNumberGroup_1.CreateFromDiscriminatorValue)?.AsList(); } },
                { "errors", n => { Errors = n.GetCollectionOfObjectValues<global::Soenneker.Bandwidth.OpenApiClient.Models.JsonDldaOrderResponsePayload_1_errors>(global::Soenneker.Bandwidth.OpenApiClient.Models.JsonDldaOrderResponsePayload_1_errors.CreateFromDiscriminatorValue)?.AsList(); } },
                { "lastModifiedDate", n => { LastModifiedDate = n.GetDateTimeOffsetValue(); } },
                { "orderCreateDate", n => { OrderCreateDate = n.GetStringValue(); } },
                { "orderId", n => { OrderId = n.GetStringValue(); } },
                { "processingStatus", n => { ProcessingStatus = n.GetEnumValue<global::Soenneker.Bandwidth.OpenApiClient.Models.JsonDldaOrderResponsePayload_1_processingStatus>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("accountId", AccountId);
            writer.WriteStringValue("createdByUser", CreatedByUser);
            writer.WriteStringValue("customerOrderId", CustomerOrderId);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Bandwidth.OpenApiClient.Models.JsonDldaPhoneNumberGroup_1>("dldaPhoneNumberGroups", DldaPhoneNumberGroups);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Bandwidth.OpenApiClient.Models.JsonDldaOrderResponsePayload_1_errors>("errors", Errors);
            writer.WriteDateTimeOffsetValue("lastModifiedDate", LastModifiedDate);
            writer.WriteStringValue("orderCreateDate", OrderCreateDate);
            writer.WriteStringValue("orderId", OrderId);
            writer.WriteEnumValue<global::Soenneker.Bandwidth.OpenApiClient.Models.JsonDldaOrderResponsePayload_1_processingStatus>("processingStatus", ProcessingStatus);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
