// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Bandwidth.OpenApiClient.Models
{
    /// <summary>[DNI-Only](#section/DNI-Only). The current delivery status of the phone number.- ACTIVE: A message was successfully sent to the number (delivery code 0).- DEACTIVATED: A message was not delivered to a number (delivery code 720)- UNKNOWN: Bandwidth cannot find an delivery status entry for the number.- NOT_ENABLED: The phone number is not enabled for messaging, so there is no delivery status information.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum LatestMessageDeliveryStatusEnum
    {
        [EnumMember(Value = "ACTIVE")]
        #pragma warning disable CS1591
        Active,
        #pragma warning restore CS1591
        [EnumMember(Value = "DEACTIVATED")]
        #pragma warning disable CS1591
        Deactivated,
        #pragma warning restore CS1591
        [EnumMember(Value = "UNKNOWN")]
        #pragma warning disable CS1591
        Unknown,
        #pragma warning restore CS1591
        [EnumMember(Value = "NOT_ENABLED")]
        #pragma warning disable CS1591
        NotEnabled,
        #pragma warning restore CS1591
    }
}
