// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Bandwidth.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ListEndpoints_1_endpoints_provisioningStatus
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "PROVISIONED")]
        #pragma warning disable CS1591
        PROVISIONED,
        #pragma warning restore CS1591
        [EnumMember(Value = "NEEDS UPDATE")]
        #pragma warning disable CS1591
        NEEDSUPDATE,
        #pragma warning restore CS1591
        [EnumMember(Value = "PRE-PROVISIONED")]
        #pragma warning disable CS1591
        PREPROVISIONED,
        #pragma warning restore CS1591
    }
}
