// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Bandwidth.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class MultiChannelChannelListRBMResponseObject_1 : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The ID of the Application your from number or senderId is associated with in the Bandwidth App.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ApplicationId { get; set; }
#nullable restore
#else
        public string ApplicationId { get; set; }
#endif
        /// <summary>The channel of the multi-channel message.</summary>
        public global::Soenneker.Bandwidth.OpenApiClient.Models.MultiChannelMessageChannelEnum_1? Channel { get; set; }
        /// <summary>The content of the message.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bandwidth.OpenApiClient.Models.MultiChannelChannelListRBMResponseObject_1.MultiChannelChannelListRBMResponseObject_1_content? Content { get; set; }
#nullable restore
#else
        public global::Soenneker.Bandwidth.OpenApiClient.Models.MultiChannelChannelListRBMResponseObject_1.MultiChannelChannelListRBMResponseObject_1_content Content { get; set; }
#endif
        /// <summary>The sender ID of the message. This could be an alphanumeric sender ID.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? From { get; set; }
#nullable restore
#else
        public string From { get; set; }
#endif
        /// <summary>The Bandwidth senderId associated with the message. Identical to &apos;from&apos;.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Owner { get; set; }
#nullable restore
#else
        public string Owner { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bandwidth.OpenApiClient.Models.MultiChannelChannelListRBMResponseObject_1"/> and sets the default values.
        /// </summary>
        public MultiChannelChannelListRBMResponseObject_1()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bandwidth.OpenApiClient.Models.MultiChannelChannelListRBMResponseObject_1"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Bandwidth.OpenApiClient.Models.MultiChannelChannelListRBMResponseObject_1 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Bandwidth.OpenApiClient.Models.MultiChannelChannelListRBMResponseObject_1();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "applicationId", n => { ApplicationId = n.GetStringValue(); } },
                { "channel", n => { Channel = n.GetEnumValue<global::Soenneker.Bandwidth.OpenApiClient.Models.MultiChannelMessageChannelEnum_1>(); } },
                { "content", n => { Content = n.GetObjectValue<global::Soenneker.Bandwidth.OpenApiClient.Models.MultiChannelChannelListRBMResponseObject_1.MultiChannelChannelListRBMResponseObject_1_content>(global::Soenneker.Bandwidth.OpenApiClient.Models.MultiChannelChannelListRBMResponseObject_1.MultiChannelChannelListRBMResponseObject_1_content.CreateFromDiscriminatorValue); } },
                { "from", n => { From = n.GetStringValue(); } },
                { "owner", n => { Owner = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("applicationId", ApplicationId);
            writer.WriteEnumValue<global::Soenneker.Bandwidth.OpenApiClient.Models.MultiChannelMessageChannelEnum_1>("channel", Channel);
            writer.WriteObjectValue<global::Soenneker.Bandwidth.OpenApiClient.Models.MultiChannelChannelListRBMResponseObject_1.MultiChannelChannelListRBMResponseObject_1_content>("content", Content);
            writer.WriteStringValue("from", From);
            writer.WriteStringValue("owner", Owner);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Bandwidth.OpenApiClient.Models.RbmMessageContentRichCard_1"/>, <see cref="global::Soenneker.Bandwidth.OpenApiClient.Models.RbmMessageContentText_1"/>, <see cref="global::Soenneker.Bandwidth.OpenApiClient.Models.RbmMessageMedia_1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class MultiChannelChannelListRBMResponseObject_1_content : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Bandwidth.OpenApiClient.Models.RbmMessageContentRichCard_1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Bandwidth.OpenApiClient.Models.RbmMessageContentRichCard_1? RbmMessageContentRichCard1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Bandwidth.OpenApiClient.Models.RbmMessageContentRichCard_1 RbmMessageContentRichCard1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Bandwidth.OpenApiClient.Models.RbmMessageContentText_1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Bandwidth.OpenApiClient.Models.RbmMessageContentText_1? RbmMessageContentText1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Bandwidth.OpenApiClient.Models.RbmMessageContentText_1 RbmMessageContentText1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Bandwidth.OpenApiClient.Models.RbmMessageMedia_1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Bandwidth.OpenApiClient.Models.RbmMessageMedia_1? RbmMessageMedia1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Bandwidth.OpenApiClient.Models.RbmMessageMedia_1 RbmMessageMedia1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Bandwidth.OpenApiClient.Models.MultiChannelChannelListRBMResponseObject_1.MultiChannelChannelListRBMResponseObject_1_content"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Bandwidth.OpenApiClient.Models.MultiChannelChannelListRBMResponseObject_1.MultiChannelChannelListRBMResponseObject_1_content CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
                var result = new global::Soenneker.Bandwidth.OpenApiClient.Models.MultiChannelChannelListRBMResponseObject_1.MultiChannelChannelListRBMResponseObject_1_content();
                if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.RbmMessageContentRichCard1 = new global::Soenneker.Bandwidth.OpenApiClient.Models.RbmMessageContentRichCard_1();
                }
                else if("RbmMessageContentText_1".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.RbmMessageContentText1 = new global::Soenneker.Bandwidth.OpenApiClient.Models.RbmMessageContentText_1();
                }
                else if("RbmMessageMedia_1".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.RbmMessageMedia1 = new global::Soenneker.Bandwidth.OpenApiClient.Models.RbmMessageMedia_1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(RbmMessageContentRichCard1 != null)
                {
                    return RbmMessageContentRichCard1.GetFieldDeserializers();
                }
                else if(RbmMessageContentText1 != null)
                {
                    return RbmMessageContentText1.GetFieldDeserializers();
                }
                else if(RbmMessageMedia1 != null)
                {
                    return RbmMessageMedia1.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(RbmMessageContentRichCard1 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Bandwidth.OpenApiClient.Models.RbmMessageContentRichCard_1>(null, RbmMessageContentRichCard1);
                }
                else if(RbmMessageContentText1 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Bandwidth.OpenApiClient.Models.RbmMessageContentText_1>(null, RbmMessageContentText1);
                }
                else if(RbmMessageMedia1 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Bandwidth.OpenApiClient.Models.RbmMessageMedia_1>(null, RbmMessageMedia1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
