// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Bandwidth.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class MultiChannelChannelListRBMResponseObject : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The ID of the Application your from number or senderId is associated with in the Bandwidth App.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ApplicationId { get; set; }
#nullable restore
#else
        public string ApplicationId { get; set; }
#endif
        /// <summary>The channel of the multi-channel message.</summary>
        public global::Soenneker.Bandwidth.OpenApiClient.Models.MultiChannelMessageChannelEnum? Channel { get; set; }
        /// <summary>The content of the message.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bandwidth.OpenApiClient.Models.MultiChannelChannelListRBMResponseObject.MultiChannelChannelListRBMResponseObject_content? Content { get; set; }
#nullable restore
#else
        public global::Soenneker.Bandwidth.OpenApiClient.Models.MultiChannelChannelListRBMResponseObject.MultiChannelChannelListRBMResponseObject_content Content { get; set; }
#endif
        /// <summary>The sender ID of the message. This could be an alphanumeric sender ID.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? From { get; set; }
#nullable restore
#else
        public string From { get; set; }
#endif
        /// <summary>The Bandwidth senderId associated with the message. Identical to &apos;from&apos;.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Owner { get; set; }
#nullable restore
#else
        public string Owner { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bandwidth.OpenApiClient.Models.MultiChannelChannelListRBMResponseObject"/> and sets the default values.
        /// </summary>
        public MultiChannelChannelListRBMResponseObject()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bandwidth.OpenApiClient.Models.MultiChannelChannelListRBMResponseObject"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Bandwidth.OpenApiClient.Models.MultiChannelChannelListRBMResponseObject CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Bandwidth.OpenApiClient.Models.MultiChannelChannelListRBMResponseObject();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "applicationId", n => { ApplicationId = n.GetStringValue(); } },
                { "channel", n => { Channel = n.GetEnumValue<global::Soenneker.Bandwidth.OpenApiClient.Models.MultiChannelMessageChannelEnum>(); } },
                { "content", n => { Content = n.GetObjectValue<global::Soenneker.Bandwidth.OpenApiClient.Models.MultiChannelChannelListRBMResponseObject.MultiChannelChannelListRBMResponseObject_content>(global::Soenneker.Bandwidth.OpenApiClient.Models.MultiChannelChannelListRBMResponseObject.MultiChannelChannelListRBMResponseObject_content.CreateFromDiscriminatorValue); } },
                { "from", n => { From = n.GetStringValue(); } },
                { "owner", n => { Owner = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("applicationId", ApplicationId);
            writer.WriteEnumValue<global::Soenneker.Bandwidth.OpenApiClient.Models.MultiChannelMessageChannelEnum>("channel", Channel);
            writer.WriteObjectValue<global::Soenneker.Bandwidth.OpenApiClient.Models.MultiChannelChannelListRBMResponseObject.MultiChannelChannelListRBMResponseObject_content>("content", Content);
            writer.WriteStringValue("from", From);
            writer.WriteStringValue("owner", Owner);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Bandwidth.OpenApiClient.Models.RbmMessageContentRichCard"/>, <see cref="global::Soenneker.Bandwidth.OpenApiClient.Models.RbmMessageContentText"/>, <see cref="global::Soenneker.Bandwidth.OpenApiClient.Models.RbmMessageMedia"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class MultiChannelChannelListRBMResponseObject_content : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Bandwidth.OpenApiClient.Models.RbmMessageContentRichCard"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Bandwidth.OpenApiClient.Models.RbmMessageContentRichCard? RbmMessageContentRichCard { get; set; }
#nullable restore
#else
            public global::Soenneker.Bandwidth.OpenApiClient.Models.RbmMessageContentRichCard RbmMessageContentRichCard { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Bandwidth.OpenApiClient.Models.RbmMessageContentText"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Bandwidth.OpenApiClient.Models.RbmMessageContentText? RbmMessageContentText { get; set; }
#nullable restore
#else
            public global::Soenneker.Bandwidth.OpenApiClient.Models.RbmMessageContentText RbmMessageContentText { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Bandwidth.OpenApiClient.Models.RbmMessageMedia"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Bandwidth.OpenApiClient.Models.RbmMessageMedia? RbmMessageMedia { get; set; }
#nullable restore
#else
            public global::Soenneker.Bandwidth.OpenApiClient.Models.RbmMessageMedia RbmMessageMedia { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Bandwidth.OpenApiClient.Models.MultiChannelChannelListRBMResponseObject.MultiChannelChannelListRBMResponseObject_content"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Bandwidth.OpenApiClient.Models.MultiChannelChannelListRBMResponseObject.MultiChannelChannelListRBMResponseObject_content CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
                var result = new global::Soenneker.Bandwidth.OpenApiClient.Models.MultiChannelChannelListRBMResponseObject.MultiChannelChannelListRBMResponseObject_content();
                if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.RbmMessageContentRichCard = new global::Soenneker.Bandwidth.OpenApiClient.Models.RbmMessageContentRichCard();
                }
                else if("RbmMessageContentText".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.RbmMessageContentText = new global::Soenneker.Bandwidth.OpenApiClient.Models.RbmMessageContentText();
                }
                else if("RbmMessageMedia".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.RbmMessageMedia = new global::Soenneker.Bandwidth.OpenApiClient.Models.RbmMessageMedia();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(RbmMessageContentRichCard != null)
                {
                    return RbmMessageContentRichCard.GetFieldDeserializers();
                }
                else if(RbmMessageContentText != null)
                {
                    return RbmMessageContentText.GetFieldDeserializers();
                }
                else if(RbmMessageMedia != null)
                {
                    return RbmMessageMedia.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(RbmMessageContentRichCard != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Bandwidth.OpenApiClient.Models.RbmMessageContentRichCard>(null, RbmMessageContentRichCard);
                }
                else if(RbmMessageContentText != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Bandwidth.OpenApiClient.Models.RbmMessageContentText>(null, RbmMessageContentText);
                }
                else if(RbmMessageMedia != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Bandwidth.OpenApiClient.Models.RbmMessageMedia>(null, RbmMessageMedia);
                }
            }
        }
    }
}
#pragma warning restore CS0618
