// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Bandwidth.OpenApiClient.Models
{
    /// <summary>Type of product added to cart.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum OrderProductProductType
    {
        [EnumMember(Value = "DID")]
        #pragma warning disable CS1591
        Did,
        #pragma warning restore CS1591
        [EnumMember(Value = "CAPACITY")]
        #pragma warning disable CS1591
        Capacity,
        #pragma warning restore CS1591
        [EnumMember(Value = "CREDIT_PACKAGE")]
        #pragma warning disable CS1591
        CreditPackage,
        #pragma warning restore CS1591
    }
}
