// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Bandwidth.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PhoneNumberOptionsJson : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Telephone Number in E.164 format.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CallForward { get; set; }
#nullable restore
#else
        public string CallForward { get; set; }
#endif
        /// <summary>The callingNameDisplay property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CallingNameDisplay { get; set; }
#nullable restore
#else
        public string CallingNameDisplay { get; set; }
#endif
        /// <summary>The callVerificationEnabled property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CallVerificationEnabled { get; set; }
#nullable restore
#else
        public string CallVerificationEnabled { get; set; }
#endif
        /// <summary>The finalDestinationUri property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FinalDestinationUri { get; set; }
#nullable restore
#else
        public string FinalDestinationUri { get; set; }
#endif
        /// <summary>The numberFormat property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NumberFormat { get; set; }
#nullable restore
#else
        public string NumberFormat { get; set; }
#endif
        /// <summary>The pindropEnabled property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PindropEnabled { get; set; }
#nullable restore
#else
        public string PindropEnabled { get; set; }
#endif
        /// <summary>The portOutPasscode property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PortOutPasscode { get; set; }
#nullable restore
#else
        public string PortOutPasscode { get; set; }
#endif
        /// <summary>The rewriteUser property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RewriteUser { get; set; }
#nullable restore
#else
        public string RewriteUser { get; set; }
#endif
        /// <summary>The rpidFormat property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RpidFormat { get; set; }
#nullable restore
#else
        public string RpidFormat { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bandwidth.OpenApiClient.Models.PhoneNumberOptionsJson"/> and sets the default values.
        /// </summary>
        public PhoneNumberOptionsJson()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bandwidth.OpenApiClient.Models.PhoneNumberOptionsJson"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Bandwidth.OpenApiClient.Models.PhoneNumberOptionsJson CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Bandwidth.OpenApiClient.Models.PhoneNumberOptionsJson();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "callForward", n => { CallForward = n.GetStringValue(); } },
                { "callVerificationEnabled", n => { CallVerificationEnabled = n.GetStringValue(); } },
                { "callingNameDisplay", n => { CallingNameDisplay = n.GetStringValue(); } },
                { "finalDestinationUri", n => { FinalDestinationUri = n.GetStringValue(); } },
                { "numberFormat", n => { NumberFormat = n.GetStringValue(); } },
                { "pindropEnabled", n => { PindropEnabled = n.GetStringValue(); } },
                { "portOutPasscode", n => { PortOutPasscode = n.GetStringValue(); } },
                { "rewriteUser", n => { RewriteUser = n.GetStringValue(); } },
                { "rpidFormat", n => { RpidFormat = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("callForward", CallForward);
            writer.WriteStringValue("callingNameDisplay", CallingNameDisplay);
            writer.WriteStringValue("callVerificationEnabled", CallVerificationEnabled);
            writer.WriteStringValue("finalDestinationUri", FinalDestinationUri);
            writer.WriteStringValue("numberFormat", NumberFormat);
            writer.WriteStringValue("pindropEnabled", PindropEnabled);
            writer.WriteStringValue("portOutPasscode", PortOutPasscode);
            writer.WriteStringValue("rewriteUser", RewriteUser);
            writer.WriteStringValue("rpidFormat", RpidFormat);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
