// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Bandwidth.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum PhoneNumberServiceStatus
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "IN_SERVICE")]
        #pragma warning disable CS1591
        InService,
        #pragma warning restore CS1591
        [EnumMember(Value = "READY_TO_ACTIVATE")]
        #pragma warning disable CS1591
        ReadyToActivate,
        #pragma warning restore CS1591
        [EnumMember(Value = "ACTIVATION_REQUIREMENTS_NOT_MET")]
        #pragma warning disable CS1591
        ActivationRequirementsNotMet,
        #pragma warning restore CS1591
        [EnumMember(Value = "ACCOUNT_NOT_CONFIGURED")]
        #pragma warning disable CS1591
        AccountNotConfigured,
        #pragma warning restore CS1591
        [EnumMember(Value = "NOT_SUPPORTED")]
        #pragma warning disable CS1591
        NotSupported,
        #pragma warning restore CS1591
    }
}
