// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Bandwidth.OpenApiClient.Models
{
    /// <summary>SUCCESS message will indicate that the operation was performed successfully.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum RequestAddressVerificationResponse_status
    {
        [EnumMember(Value = "SUCCESS")]
        #pragma warning disable CS1591
        SUCCESS,
        #pragma warning restore CS1591
        [EnumMember(Value = "PARTIAL")]
        #pragma warning disable CS1591
        PARTIAL,
        #pragma warning restore CS1591
        [EnumMember(Value = "WARNING")]
        #pragma warning disable CS1591
        WARNING,
        #pragma warning restore CS1591
        [EnumMember(Value = "ERROR")]
        #pragma warning disable CS1591
        ERROR,
        #pragma warning restore CS1591
    }
}
