// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Bandwidth.OpenApiClient.Models
{
    /// <summary>
    /// Details of the Requirements package
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RequirementsPackageData : IAdditionalDataHolder, IParsable
    {
        /// <summary>Captures the acknowledgments on requirements package submission. Mandatory when status is provided</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bandwidth.OpenApiClient.Models.RequirementsPackageAcknowledgements? Acknowledgements { get; set; }
#nullable restore
#else
        public global::Soenneker.Bandwidth.OpenApiClient.Models.RequirementsPackageAcknowledgements Acknowledgements { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Callback URL</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Callback { get; set; }
#nullable restore
#else
        public string Callback { get; set; }
#endif
        /// <summary>Country code in ISO 3166-1 alpha-3 format</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CountryCodeA3 { get; set; }
#nullable restore
#else
        public string CountryCodeA3 { get; set; }
#endif
        /// <summary>The createdDateTime property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bandwidth.OpenApiClient.Models.RequirementsPackageData_createdDateTime? CreatedDateTime { get; private set; }
#nullable restore
#else
        public global::Soenneker.Bandwidth.OpenApiClient.Models.RequirementsPackageData_createdDateTime CreatedDateTime { get; private set; }
#endif
        /// <summary>A custom reference name.It can be used for your own reference to the item to easily identify one of your customers,requirements package, enduser etc.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomReference { get; set; }
#nullable restore
#else
        public string CustomReference { get; set; }
#endif
        /// <summary>The email property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Email { get; set; }
#nullable restore
#else
        public string Email { get; set; }
#endif
        /// <summary>The type of end user</summary>
        public global::Soenneker.Bandwidth.OpenApiClient.Models.EndUserTypeEnum? EndUserType { get; set; }
        /// <summary>The type of phone number.</summary>
        public global::Soenneker.Bandwidth.OpenApiClient.Models.PhoneNumberTypeEnum? PhoneNumberType { get; set; }
        /// <summary>Remarks provided by the user or admin</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Remarks { get; set; }
#nullable restore
#else
        public string Remarks { get; set; }
#endif
        /// <summary>The requirementsPackageId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bandwidth.OpenApiClient.Models.RequirementsPackageData_requirementsPackageId? RequirementsPackageId { get; private set; }
#nullable restore
#else
        public global::Soenneker.Bandwidth.OpenApiClient.Models.RequirementsPackageData_requirementsPackageId RequirementsPackageId { get; private set; }
#endif
        /// <summary>Status of the Requirements package</summary>
        public global::Soenneker.Bandwidth.OpenApiClient.Models.RequirementsPackageStatusEnum? Status { get; set; }
        /// <summary>The updatedDateTime property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bandwidth.OpenApiClient.Models.RequirementsPackageData_updatedDateTime? UpdatedDateTime { get; private set; }
#nullable restore
#else
        public global::Soenneker.Bandwidth.OpenApiClient.Models.RequirementsPackageData_updatedDateTime UpdatedDateTime { get; private set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bandwidth.OpenApiClient.Models.RequirementsPackageData"/> and sets the default values.
        /// </summary>
        public RequirementsPackageData()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bandwidth.OpenApiClient.Models.RequirementsPackageData"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Bandwidth.OpenApiClient.Models.RequirementsPackageData CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Bandwidth.OpenApiClient.Models.RequirementsPackageData();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "acknowledgements", n => { Acknowledgements = n.GetObjectValue<global::Soenneker.Bandwidth.OpenApiClient.Models.RequirementsPackageAcknowledgements>(global::Soenneker.Bandwidth.OpenApiClient.Models.RequirementsPackageAcknowledgements.CreateFromDiscriminatorValue); } },
                { "callback", n => { Callback = n.GetStringValue(); } },
                { "countryCodeA3", n => { CountryCodeA3 = n.GetStringValue(); } },
                { "createdDateTime", n => { CreatedDateTime = n.GetObjectValue<global::Soenneker.Bandwidth.OpenApiClient.Models.RequirementsPackageData_createdDateTime>(global::Soenneker.Bandwidth.OpenApiClient.Models.RequirementsPackageData_createdDateTime.CreateFromDiscriminatorValue); } },
                { "customReference", n => { CustomReference = n.GetStringValue(); } },
                { "email", n => { Email = n.GetStringValue(); } },
                { "endUserType", n => { EndUserType = n.GetEnumValue<global::Soenneker.Bandwidth.OpenApiClient.Models.EndUserTypeEnum>(); } },
                { "phoneNumberType", n => { PhoneNumberType = n.GetEnumValue<global::Soenneker.Bandwidth.OpenApiClient.Models.PhoneNumberTypeEnum>(); } },
                { "remarks", n => { Remarks = n.GetStringValue(); } },
                { "requirementsPackageId", n => { RequirementsPackageId = n.GetObjectValue<global::Soenneker.Bandwidth.OpenApiClient.Models.RequirementsPackageData_requirementsPackageId>(global::Soenneker.Bandwidth.OpenApiClient.Models.RequirementsPackageData_requirementsPackageId.CreateFromDiscriminatorValue); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Bandwidth.OpenApiClient.Models.RequirementsPackageStatusEnum>(); } },
                { "updatedDateTime", n => { UpdatedDateTime = n.GetObjectValue<global::Soenneker.Bandwidth.OpenApiClient.Models.RequirementsPackageData_updatedDateTime>(global::Soenneker.Bandwidth.OpenApiClient.Models.RequirementsPackageData_updatedDateTime.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Bandwidth.OpenApiClient.Models.RequirementsPackageAcknowledgements>("acknowledgements", Acknowledgements);
            writer.WriteStringValue("callback", Callback);
            writer.WriteStringValue("countryCodeA3", CountryCodeA3);
            writer.WriteStringValue("customReference", CustomReference);
            writer.WriteStringValue("email", Email);
            writer.WriteEnumValue<global::Soenneker.Bandwidth.OpenApiClient.Models.EndUserTypeEnum>("endUserType", EndUserType);
            writer.WriteEnumValue<global::Soenneker.Bandwidth.OpenApiClient.Models.PhoneNumberTypeEnum>("phoneNumberType", PhoneNumberType);
            writer.WriteStringValue("remarks", Remarks);
            writer.WriteEnumValue<global::Soenneker.Bandwidth.OpenApiClient.Models.RequirementsPackageStatusEnum>("status", Status);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
