// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Bandwidth.OpenApiClient.Models
{
    /// <summary>The country the short code was registered in.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ShortCodeHistoryCountry
    {
        [EnumMember(Value = "USA")]
        #pragma warning disable CS1591
        Usa,
        #pragma warning restore CS1591
        [EnumMember(Value = "CAN")]
        #pragma warning disable CS1591
        Can,
        #pragma warning restore CS1591
    }
}
