// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Bandwidth.OpenApiClient.Models
{
    /// <summary>If at least one carrier status is ACTIVE or PENDING, the status will be ACTIVE. If all carrier statues are INACTIVE, the status will be INACTIVE.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ShortCode_1_status
    {
        [EnumMember(Value = "ACTIVE")]
        #pragma warning disable CS1591
        ACTIVE,
        #pragma warning restore CS1591
        [EnumMember(Value = "EXPIRED")]
        #pragma warning disable CS1591
        EXPIRED,
        #pragma warning restore CS1591
        [EnumMember(Value = "SUSPENDED")]
        #pragma warning disable CS1591
        SUSPENDED,
        #pragma warning restore CS1591
        [EnumMember(Value = "INACTIVE")]
        #pragma warning disable CS1591
        INACTIVE,
        #pragma warning restore CS1591
    }
}
