// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Bandwidth.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum SsSendToCustomer_1
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "NONE")]
        #pragma warning disable CS1591
        NONE,
        #pragma warning restore CS1591
        [EnumMember(Value = "VERSTAT")]
        #pragma warning disable CS1591
        VERSTAT,
        #pragma warning restore CS1591
        [EnumMember(Value = "ENH_VERSTAT")]
        #pragma warning disable CS1591
        ENH_VERSTAT,
        #pragma warning restore CS1591
        [EnumMember(Value = "VERSTAT_AND_IDENTITY")]
        #pragma warning disable CS1591
        VERSTAT_AND_IDENTITY,
        #pragma warning restore CS1591
        [EnumMember(Value = "ENH_VERSTAT_AND_IDENTITY")]
        #pragma warning disable CS1591
        ENH_VERSTAT_AND_IDENTITY,
        #pragma warning restore CS1591
        [EnumMember(Value = "IDENTITY")]
        #pragma warning disable CS1591
        IDENTITY,
        #pragma warning restore CS1591
    }
}
