// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Bandwidth.OpenApiClient.Models
{
    /// <summary>If residential, order will be rejected if a BusinessName is entered.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SubscriberPatchJson_1_subscriberType
    {
        [EnumMember(Value = "BUSINESS")]
        #pragma warning disable CS1591
        BUSINESS,
        #pragma warning restore CS1591
        [EnumMember(Value = "RESIDENTIAL")]
        #pragma warning disable CS1591
        RESIDENTIAL,
        #pragma warning restore CS1591
        [EnumMember(Value = "GENERIC")]
        #pragma warning disable CS1591
        GENERIC,
        #pragma warning restore CS1591
    }
}
