// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Bandwidth.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TfvStatus : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Whether a Toll-Free Verification is blocked. This attribute will only be defined when the number is blocked.</summary>
        public bool? Blocked { get; set; }
        /// <summary>The reason why the Toll-Free Verification is blocked. This attribute will only be defined when the number is blocked.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BlockedReason { get; set; }
#nullable restore
#else
        public string BlockedReason { get; set; }
#endif
        /// <summary>Date and time the verification request was created.</summary>
        public DateTimeOffset? CreatedDateTime { get; set; }
        /// <summary>The token provided by Campaign Verify to validate your political use case. Only required for 527 political organizations. If you are not a 527 political organization, this field should be omitted. Supplying an empty string will likely result in rejection.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CvToken { get; set; }
#nullable restore
#else
        public string CvToken { get; set; }
#endif
        /// <summary>Explanation for why a verification request was declined.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeclineReasonDescription { get; set; }
#nullable restore
#else
        public string DeclineReasonDescription { get; set; }
#endif
        /// <summary>Unique identifier (UUID) generated by Bandwidth to assist in tracking the verification status of a toll-free number - included in all webhook payloads.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InternalTicketNumber { get; set; }
#nullable restore
#else
        public string InternalTicketNumber { get; set; }
#endif
        /// <summary>Date and time the verification request was last modified.</summary>
        public DateTimeOffset? ModifiedDateTime { get; set; }
        /// <summary>Toll-free telephone number in E.164 format.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PhoneNumber { get; set; }
#nullable restore
#else
        public string PhoneNumber { get; set; }
#endif
        /// <summary>Whether a Toll-Free Verification request qualifies for resubmission via PUT.</summary>
        public bool? ResubmitAllowed { get; set; }
        /// <summary>The status property</summary>
        public global::Soenneker.Bandwidth.OpenApiClient.Models.TfvStatusEnum? Status { get; set; }
        /// <summary>The submission property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bandwidth.OpenApiClient.Models.TfvSubmissionInfo? Submission { get; set; }
#nullable restore
#else
        public global::Soenneker.Bandwidth.OpenApiClient.Models.TfvSubmissionInfo Submission { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bandwidth.OpenApiClient.Models.TfvStatus"/> and sets the default values.
        /// </summary>
        public TfvStatus()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bandwidth.OpenApiClient.Models.TfvStatus"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Bandwidth.OpenApiClient.Models.TfvStatus CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Bandwidth.OpenApiClient.Models.TfvStatus();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "blocked", n => { Blocked = n.GetBoolValue(); } },
                { "blockedReason", n => { BlockedReason = n.GetStringValue(); } },
                { "createdDateTime", n => { CreatedDateTime = n.GetDateTimeOffsetValue(); } },
                { "cvToken", n => { CvToken = n.GetStringValue(); } },
                { "declineReasonDescription", n => { DeclineReasonDescription = n.GetStringValue(); } },
                { "internalTicketNumber", n => { InternalTicketNumber = n.GetStringValue(); } },
                { "modifiedDateTime", n => { ModifiedDateTime = n.GetDateTimeOffsetValue(); } },
                { "phoneNumber", n => { PhoneNumber = n.GetStringValue(); } },
                { "resubmitAllowed", n => { ResubmitAllowed = n.GetBoolValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Bandwidth.OpenApiClient.Models.TfvStatusEnum>(); } },
                { "submission", n => { Submission = n.GetObjectValue<global::Soenneker.Bandwidth.OpenApiClient.Models.TfvSubmissionInfo>(global::Soenneker.Bandwidth.OpenApiClient.Models.TfvSubmissionInfo.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("blocked", Blocked);
            writer.WriteStringValue("blockedReason", BlockedReason);
            writer.WriteDateTimeOffsetValue("createdDateTime", CreatedDateTime);
            writer.WriteStringValue("cvToken", CvToken);
            writer.WriteStringValue("declineReasonDescription", DeclineReasonDescription);
            writer.WriteStringValue("internalTicketNumber", InternalTicketNumber);
            writer.WriteDateTimeOffsetValue("modifiedDateTime", ModifiedDateTime);
            writer.WriteStringValue("phoneNumber", PhoneNumber);
            writer.WriteBoolValue("resubmitAllowed", ResubmitAllowed);
            writer.WriteEnumValue<global::Soenneker.Bandwidth.OpenApiClient.Models.TfvStatusEnum>("status", Status);
            writer.WriteObjectValue<global::Soenneker.Bandwidth.OpenApiClient.Models.TfvSubmissionInfo>("submission", Submission);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
