// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Bandwidth.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TnDetailsMessagingSettingsJson : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The a2pState property</summary>
        public global::Soenneker.Bandwidth.OpenApiClient.Models.TnDetailsMessagingSettingsJson_a2pState? A2pState { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The campaignFullyProvisioned property</summary>
        public bool? CampaignFullyProvisioned { get; set; }
        /// <summary>The campaignId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CampaignId { get; set; }
#nullable restore
#else
        public string CampaignId { get; set; }
#endif
        /// <summary>The messageClass property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MessageClass { get; set; }
#nullable restore
#else
        public string MessageClass { get; set; }
#endif
        /// <summary>The phoneNumberDetailsNnRoute property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bandwidth.OpenApiClient.Models.TnDetailsNnRouteJson? PhoneNumberDetailsNnRoute { get; set; }
#nullable restore
#else
        public global::Soenneker.Bandwidth.OpenApiClient.Models.TnDetailsNnRouteJson PhoneNumberDetailsNnRoute { get; set; }
#endif
        /// <summary>The smsEnabled property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SmsEnabled { get; set; }
#nullable restore
#else
        public string SmsEnabled { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bandwidth.OpenApiClient.Models.TnDetailsMessagingSettingsJson"/> and sets the default values.
        /// </summary>
        public TnDetailsMessagingSettingsJson()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bandwidth.OpenApiClient.Models.TnDetailsMessagingSettingsJson"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Bandwidth.OpenApiClient.Models.TnDetailsMessagingSettingsJson CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Bandwidth.OpenApiClient.Models.TnDetailsMessagingSettingsJson();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "a2pState", n => { A2pState = n.GetEnumValue<global::Soenneker.Bandwidth.OpenApiClient.Models.TnDetailsMessagingSettingsJson_a2pState>(); } },
                { "campaignFullyProvisioned", n => { CampaignFullyProvisioned = n.GetBoolValue(); } },
                { "campaignId", n => { CampaignId = n.GetStringValue(); } },
                { "messageClass", n => { MessageClass = n.GetStringValue(); } },
                { "phoneNumberDetailsNnRoute", n => { PhoneNumberDetailsNnRoute = n.GetObjectValue<global::Soenneker.Bandwidth.OpenApiClient.Models.TnDetailsNnRouteJson>(global::Soenneker.Bandwidth.OpenApiClient.Models.TnDetailsNnRouteJson.CreateFromDiscriminatorValue); } },
                { "smsEnabled", n => { SmsEnabled = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Bandwidth.OpenApiClient.Models.TnDetailsMessagingSettingsJson_a2pState>("a2pState", A2pState);
            writer.WriteBoolValue("campaignFullyProvisioned", CampaignFullyProvisioned);
            writer.WriteStringValue("campaignId", CampaignId);
            writer.WriteStringValue("messageClass", MessageClass);
            writer.WriteObjectValue<global::Soenneker.Bandwidth.OpenApiClient.Models.TnDetailsNnRouteJson>("phoneNumberDetailsNnRoute", PhoneNumberDetailsNnRoute);
            writer.WriteStringValue("smsEnabled", SmsEnabled);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
