// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Bandwidth.OpenApiClient.Models
{
    /// <summary>The processing status of this order. Values may be: PROCESSING, COMPLETED, FAILED. PROCESSING means that the system is still processing the order. COMPLETED means that the order has been successfully completed. FAILED means that errors occurred while processing the order, and that the order did not make any changes to the system.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TnListUpdateResponseJsonProcessingStatus
    {
        [EnumMember(Value = "DRAFT")]
        #pragma warning disable CS1591
        Draft,
        #pragma warning restore CS1591
        [EnumMember(Value = "PARTIAL")]
        #pragma warning disable CS1591
        Partial,
        #pragma warning restore CS1591
        [EnumMember(Value = "COMPLETED")]
        #pragma warning disable CS1591
        Completed,
        #pragma warning restore CS1591
        [EnumMember(Value = "CANCELED")]
        #pragma warning disable CS1591
        Canceled,
        #pragma warning restore CS1591
        [EnumMember(Value = "VALIDATE_DRAFT_TNS")]
        #pragma warning disable CS1591
        ValidateDraftTns,
        #pragma warning restore CS1591
        [EnumMember(Value = "VALID_DRAFT_TNS")]
        #pragma warning disable CS1591
        ValidDraftTns,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_DRAFT_TNS")]
        #pragma warning disable CS1591
        InvalidDraftTns,
        #pragma warning restore CS1591
    }
}
