// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Bandwidth.OpenApiClient.Models
{
    /// <summary>The status of the user</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum UserManagementStatusEnum
    {
        [EnumMember(Value = "STAGED")]
        #pragma warning disable CS1591
        STAGED,
        #pragma warning restore CS1591
        [EnumMember(Value = "PROVISIONED")]
        #pragma warning disable CS1591
        PROVISIONED,
        #pragma warning restore CS1591
        [EnumMember(Value = "ACTIVE")]
        #pragma warning disable CS1591
        ACTIVE,
        #pragma warning restore CS1591
        [EnumMember(Value = "PASSWORD_EXPIRED")]
        #pragma warning disable CS1591
        PASSWORD_EXPIRED,
        #pragma warning restore CS1591
        [EnumMember(Value = "LOCKED_OUT")]
        #pragma warning disable CS1591
        LOCKED_OUT,
        #pragma warning restore CS1591
        [EnumMember(Value = "RECOVERY")]
        #pragma warning disable CS1591
        RECOVERY,
        #pragma warning restore CS1591
        [EnumMember(Value = "SUSPENDED")]
        #pragma warning disable CS1591
        SUSPENDED,
        #pragma warning restore CS1591
        [EnumMember(Value = "DEPROVISIONED")]
        #pragma warning disable CS1591
        DEPROVISIONED,
        #pragma warning restore CS1591
    }
}
