// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Bandwidth.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum VerstatEnum
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "BASIC")]
        #pragma warning disable CS1591
        Basic,
        #pragma warning restore CS1591
        [EnumMember(Value = "ENHANCED")]
        #pragma warning disable CS1591
        Enhanced,
        #pragma warning restore CS1591
    }
}
