// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Bandwidth.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Vetting : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The Bandwidth-generated identifier for this entity. The TCR and Bandwidth identifiers are interchangeable in the Bandwidth APIs and either can be used to retrieve information about the entity.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BandwidthId { get; set; }
#nullable restore
#else
        public string BandwidthId { get; set; }
#endif
        /// <summary>The time the entity was created in the TCR system.</summary>
        public DateTimeOffset? CreatedDate { get; set; }
        /// <summary>The external vetting companies that can be used to vet brands. Aegis Mobile accepts standard, enhanced, political, Auth+, and RCS vetting requests; Campaign Verify (CV) vets federal political brands (import only); WMC Global supports standard vetting.</summary>
        public global::Soenneker.Bandwidth.OpenApiClient.Models.EnumVettingProviderId? EvpId { get; set; }
        /// <summary>Reasons provided by the external vetting provider for the vetting outcome.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Reasons { get; set; }
#nullable restore
#else
        public List<string> Reasons { get; set; }
#endif
        /// <summary>The date the vetting was completed.</summary>
        public DateTimeOffset? VettedDate { get; set; }
        /// <summary>The type of external vetting represented by the vetting being appealed.</summary>
        public global::Soenneker.Bandwidth.OpenApiClient.Models.EnumVettingClass? VettingClass { get; set; }
        /// <summary>Additional details from the external vetting provider.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bandwidth.OpenApiClient.Models.VettingVettingDetails? VettingDetails { get; set; }
#nullable restore
#else
        public global::Soenneker.Bandwidth.OpenApiClient.Models.VettingVettingDetails VettingDetails { get; set; }
#endif
        /// <summary>The identifier of the vetting from the external vetting provider.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VettingId { get; set; }
#nullable restore
#else
        public string VettingId { get; set; }
#endif
        /// <summary>The score assigned by the external vetting provider.</summary>
        public int? VettingScore { get; set; }
        /// <summary>The status of the external vetting.</summary>
        public global::Soenneker.Bandwidth.OpenApiClient.Models.EnumVettingStatus? VettingStatus { get; set; }
        /// <summary>The vetting token, required for Aegis vettings.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VettingToken { get; set; }
#nullable restore
#else
        public string VettingToken { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bandwidth.OpenApiClient.Models.Vetting"/> and sets the default values.
        /// </summary>
        public Vetting()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bandwidth.OpenApiClient.Models.Vetting"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Bandwidth.OpenApiClient.Models.Vetting CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Bandwidth.OpenApiClient.Models.Vetting();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bandwidthId", n => { BandwidthId = n.GetStringValue(); } },
                { "createdDate", n => { CreatedDate = n.GetDateTimeOffsetValue(); } },
                { "evpId", n => { EvpId = n.GetEnumValue<global::Soenneker.Bandwidth.OpenApiClient.Models.EnumVettingProviderId>(); } },
                { "reasons", n => { Reasons = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "vettedDate", n => { VettedDate = n.GetDateTimeOffsetValue(); } },
                { "vettingClass", n => { VettingClass = n.GetEnumValue<global::Soenneker.Bandwidth.OpenApiClient.Models.EnumVettingClass>(); } },
                { "vettingDetails", n => { VettingDetails = n.GetObjectValue<global::Soenneker.Bandwidth.OpenApiClient.Models.VettingVettingDetails>(global::Soenneker.Bandwidth.OpenApiClient.Models.VettingVettingDetails.CreateFromDiscriminatorValue); } },
                { "vettingId", n => { VettingId = n.GetStringValue(); } },
                { "vettingScore", n => { VettingScore = n.GetIntValue(); } },
                { "vettingStatus", n => { VettingStatus = n.GetEnumValue<global::Soenneker.Bandwidth.OpenApiClient.Models.EnumVettingStatus>(); } },
                { "vettingToken", n => { VettingToken = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("bandwidthId", BandwidthId);
            writer.WriteDateTimeOffsetValue("createdDate", CreatedDate);
            writer.WriteEnumValue<global::Soenneker.Bandwidth.OpenApiClient.Models.EnumVettingProviderId>("evpId", EvpId);
            writer.WriteCollectionOfPrimitiveValues<string>("reasons", Reasons);
            writer.WriteDateTimeOffsetValue("vettedDate", VettedDate);
            writer.WriteEnumValue<global::Soenneker.Bandwidth.OpenApiClient.Models.EnumVettingClass>("vettingClass", VettingClass);
            writer.WriteObjectValue<global::Soenneker.Bandwidth.OpenApiClient.Models.VettingVettingDetails>("vettingDetails", VettingDetails);
            writer.WriteStringValue("vettingId", VettingId);
            writer.WriteIntValue("vettingScore", VettingScore);
            writer.WriteEnumValue<global::Soenneker.Bandwidth.OpenApiClient.Models.EnumVettingStatus>("vettingStatus", VettingStatus);
            writer.WriteStringValue("vettingToken", VettingToken);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
