// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Bandwidth.OpenApiClient.Dash.Locationsbyuri.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Bandwidth.OpenApiClient.Dash.Locationsbyuri
{
    /// <summary>
    /// Builds and executes requests for operations under \dash\locationsbyuri
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LocationsbyuriRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Bandwidth.OpenApiClient.dash.locationsbyuri.item collection</summary>
        /// <param name="position">The 11 digit phone number for the subscriber. The &quot;tel:&quot; prefix is not supported for the URI in this operation.</param>
        /// <returns>A <see cref="global::Soenneker.Bandwidth.OpenApiClient.Dash.Locationsbyuri.Item.WithUriItemRequestBuilder"/></returns>
        public global::Soenneker.Bandwidth.OpenApiClient.Dash.Locationsbyuri.Item.WithUriItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("uri", position);
                return new global::Soenneker.Bandwidth.OpenApiClient.Dash.Locationsbyuri.Item.WithUriItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bandwidth.OpenApiClient.Dash.Locationsbyuri.LocationsbyuriRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LocationsbyuriRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/dash/locationsbyuri", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bandwidth.OpenApiClient.Dash.Locationsbyuri.LocationsbyuriRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LocationsbyuriRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/dash/locationsbyuri", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
